CREATE TABLE `visaApplications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50) NOT NULL,
	`passportNumber` varchar(50) NOT NULL,
	`passportExpiry` varchar(20) NOT NULL,
	`passportCountry` varchar(100) NOT NULL DEFAULT 'United States',
	`dateOfBirth` varchar(20) NOT NULL,
	`placeOfBirth` varchar(200),
	`visaType` enum('L_tourist','M_business','Q1_family_long','Q2_family_short','S1_dependent_long','S2_dependent_short','Z_work','X1_study_long','X2_study_short') NOT NULL DEFAULT 'L_tourist',
	`entryType` enum('single','double','multiple_6m','multiple_12m') NOT NULL DEFAULT 'single',
	`processingSpeed` enum('regular','express','rush') NOT NULL DEFAULT 'regular',
	`travelDate` varchar(20),
	`travelPurpose` text,
	`previousVisits` int DEFAULT 0,
	`serviceFee` decimal(10,2) NOT NULL,
	`consulateFee` decimal(10,2),
	`totalAmount` decimal(10,2) NOT NULL,
	`discountType` enum('none','group','returning') NOT NULL DEFAULT 'none',
	`paymentStatus` enum('unpaid','paid','refunded') NOT NULL DEFAULT 'unpaid',
	`stripePaymentIntentId` varchar(255),
	`stripeCheckoutSessionId` varchar(255),
	`paidAt` timestamp,
	`applicationStatus` enum('draft','submitted','paid','documents_received','processing','approved','rejected','completed','cancelled') NOT NULL DEFAULT 'draft',
	`adminNotes` text,
	`trackingNumber` varchar(100),
	`uploadedDocuments` text,
	`groupApplicants` text,
	`groupSize` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `visaApplications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `visaStatusHistory` (
	`id` int AUTO_INCREMENT NOT NULL,
	`applicationId` int NOT NULL,
	`fromStatus` varchar(50),
	`toStatus` varchar(50) NOT NULL,
	`changedBy` int,
	`note` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `visaStatusHistory_id` PRIMARY KEY(`id`)
);
