CREATE TABLE `accountingEntries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`entryType` enum('income','expense') NOT NULL,
	`category` enum('tour_booking','visa_service','affiliate_commission','flight_booking','hotel_booking','other_income','rent','utilities','salary','marketing','travel_cost','supplier_payment','office_supplies','software','insurance','tax_payment','bank_fee','stripe_fee','consulate_fee','other_expense') NOT NULL,
	`amount` decimal(12,2) NOT NULL,
	`currency` varchar(3) NOT NULL DEFAULT 'USD',
	`description` varchar(1000) NOT NULL,
	`bookingId` int,
	`visaApplicationId` int,
	`paymentId` int,
	`entryDate` timestamp NOT NULL,
	`receiptUrl` varchar(1024),
	`notes` text,
	`tags` varchar(500),
	`isTaxDeductible` int NOT NULL DEFAULT 0,
	`taxCategory` varchar(100),
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `accountingEntries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `invoices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`invoiceNumber` varchar(50) NOT NULL,
	`customerName` varchar(200) NOT NULL,
	`customerEmail` varchar(320),
	`customerPhone` varchar(50),
	`customerAddress` text,
	`bookingId` int,
	`visaApplicationId` int,
	`userId` int,
	`subtotal` decimal(12,2) NOT NULL,
	`taxRate` decimal(5,2) DEFAULT '0',
	`taxAmount` decimal(12,2) DEFAULT '0',
	`totalAmount` decimal(12,2) NOT NULL,
	`currency` varchar(3) NOT NULL DEFAULT 'USD',
	`lineItems` text,
	`status` enum('draft','sent','paid','overdue','cancelled') NOT NULL DEFAULT 'draft',
	`dueDate` timestamp,
	`paidAt` timestamp,
	`sentAt` timestamp,
	`pdfUrl` varchar(1024),
	`notes` text,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `invoices_id` PRIMARY KEY(`id`),
	CONSTRAINT `invoices_invoiceNumber_unique` UNIQUE(`invoiceNumber`)
);
--> statement-breakpoint
CREATE TABLE `recurringExpenses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`category` varchar(50) NOT NULL,
	`description` varchar(500) NOT NULL,
	`amount` decimal(12,2) NOT NULL,
	`currency` varchar(3) NOT NULL DEFAULT 'USD',
	`frequency` enum('monthly','quarterly','yearly') NOT NULL DEFAULT 'monthly',
	`dayOfMonth` int DEFAULT 1,
	`isTaxDeductible` int NOT NULL DEFAULT 1,
	`taxCategory` varchar(100),
	`isActive` int NOT NULL DEFAULT 1,
	`lastGeneratedAt` timestamp,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `recurringExpenses_id` PRIMARY KEY(`id`)
);
