/**
 * Happy-path Vitest for the four extracted pure helpers in toursTab.helpers.ts
 * (Phase 5 module 5B). One case per exported helper per the task spec.
 */
import { describe, expect, it } from "vitest";
import {
  filterAndSortTours,
  computeStats,
  computeStatusCounts,
  toRowData,
  type TourLike,
} from "./toursTab.helpers";

/**
 * Build a Tour fixture with sensible defaults. Override per-test.
 */
function makeTour(overrides: Partial<TourLike> = {}): TourLike {
  return {
    id: 1,
    title: "Sample Tour",
    destination: "Tokyo",
    destinationCountry: "Japan",
    destinationCity: "Tokyo",
    duration: 5,
    price: 1000,
    status: "active",
    featured: 0,
    createdAt: new Date("2026-05-15T00:00:00Z"),
    ...overrides,
  };
}

describe("filterAndSortTours", () => {
  it("filters by status=active and sorts by price-asc", () => {
    const tours: TourLike[] = [
      makeTour({ id: 1, status: "active", price: 3000 }),
      makeTour({ id: 2, status: "inactive", price: 500 }),
      makeTour({ id: 3, status: "active", price: 1500 }),
      makeTour({ id: 4, status: "draft", price: 800 }),
      makeTour({ id: 5, status: "active", price: 1000 }),
    ];

    const result = filterAndSortTours(tours, {
      statusFilter: "active",
      featuredFilter: "all",
      searchKeyword: "",
      sortBy: "price-asc",
    });

    expect(result).toHaveLength(3);
    expect(result?.map((t) => t.id)).toEqual([5, 3, 1]);
    expect(result?.[0].price).toBe(1000);
  });
});

describe("computeStats", () => {
  it("counts active / draft / featured / recent (last 7 days)", () => {
    const now = Date.now();
    const oneDayAgo = new Date(now - 24 * 60 * 60 * 1000);
    const tenDaysAgo = new Date(now - 10 * 24 * 60 * 60 * 1000);
    const tours: TourLike[] = [
      makeTour({ id: 1, status: "active", featured: 1, createdAt: oneDayAgo }),
      makeTour({ id: 2, status: "active", featured: 1, createdAt: tenDaysAgo }),
      makeTour({ id: 3, status: "active", featured: 0, createdAt: oneDayAgo }),
      makeTour({ id: 4, status: "draft", featured: 0, createdAt: tenDaysAgo }),
      makeTour({ id: 5, status: "draft", featured: 0, createdAt: oneDayAgo }),
    ];

    const stats = computeStats(tours);

    expect(stats.active).toBe(3);
    expect(stats.draft).toBe(2);
    expect(stats.featured).toBe(2);
    expect(stats.recent).toBeGreaterThanOrEqual(3);
  });
});

describe("computeStatusCounts", () => {
  it("counts all / active / inactive (inactive = non-active)", () => {
    const tours: TourLike[] = [
      makeTour({ id: 1, status: "active" }),
      makeTour({ id: 2, status: "active" }),
      makeTour({ id: 3, status: "active" }),
      makeTour({ id: 4, status: "draft" }),
      makeTour({ id: 5, status: "inactive" }),
    ];

    const counts = computeStatusCounts(tours);

    expect(counts.all).toBe(5);
    expect(counts.active).toBe(3);
    expect(counts.inactive).toBe(2);
  });
});

describe("toRowData", () => {
  it("maps all 14 fields incl. hasAiDeparturePreview from extractedDepartures", () => {
    const tour: TourLike = {
      id: 42,
      title: "Paris Spring",
      imageUrl: "https://example.com/p.jpg",
      destination: "Paris",
      destinationCountry: "France",
      destinationCity: "Paris",
      duration: 7,
      price: 2500,
      status: "active",
      featured: 1,
      isAutoGenerated: 1,
      sourceUrl: "https://supplier.example.com/tour/42",
      calibrationVerdict: "pass",
      calibrationScore: 95,
      extractedDepartures: [{ date: "2026-06-01" }],
    };

    const row = toRowData(tour);

    expect(row.id).toBe(42);
    expect(row.title).toBe("Paris Spring");
    expect(row.imageUrl).toBe("https://example.com/p.jpg");
    expect(row.destination).toBe("Paris");
    expect(row.destinationCountry).toBe("France");
    expect(row.destinationCity).toBe("Paris");
    expect(row.duration).toBe(7);
    expect(row.price).toBe(2500);
    expect(row.status).toBe("active");
    expect(row.featured).toBe(1);
    expect(row.isAutoGenerated).toBe(1);
    expect(row.sourceUrl).toBe("https://supplier.example.com/tour/42");
    expect(row.calibrationVerdict).toBe("pass");
    expect(row.calibrationScore).toBe(95);
    expect(row.hasAiDeparturePreview).toBe(true);
  });

  it("hasAiDeparturePreview is false when extractedDepartures absent", () => {
    const row = toRowData({
      id: 1,
      title: "X",
      destination: null,
      duration: 1,
      price: 0,
      status: "draft",
      featured: null,
    });
    expect(row.hasAiDeparturePreview).toBe(false);
    expect(row.destination).toBe("");
  });
});
