/**
 * ToursTab — pure derivation helpers extracted from ToursTab.tsx
 * (Phase 5 module 5B). All four helpers below are pure functions with no
 * React deps — safe to import in tests.
 *
 * Behavior preserved verbatim from the inline useMemo bodies; only the
 * surrounding `useMemo(() => …, deps)` wrapper stays in the entry file so
 * React still memoises the result.
 *
 * NOTE: `Tour` is a structural minimum — we only declare the fields the
 * helpers read. Full row typing from tRPC is deferred to v2 (see CLAUDE.md
 * §9.6 deferred-typing-cleanup track).
 */
import type { TourRowData } from "./ToursTabRow";
import type {
  FeaturedFilter,
  SortKey,
  StatusFilter,
} from "./ToursTabFilters";

/**
 * Structural minimum a Tour must satisfy for these helpers to run.
 * Fields are intentionally permissive (matches tRPC output shape).
 */
export interface TourLike {
  id: number;
  title: string;
  imageUrl?: string | null;
  destination?: string | null;
  destinationCountry?: string | null;
  destinationCity?: string | null;
  duration: number;
  price: number;
  status: "active" | "inactive" | "soldout" | "draft" | "pending_review";
  featured: number | null;
  createdAt?: string | Date | null;
  isAutoGenerated?: number | null;
  sourceUrl?: string | null;
  calibrationVerdict?: string | null;
  calibrationScore?: number | null;
  extractedDepartures?: unknown;
}

export interface FilterOptions {
  statusFilter: StatusFilter;
  featuredFilter: FeaturedFilter;
  searchKeyword: string;
  sortBy: SortKey;
}

/**
 * Filter + sort a tours list. Returns a new sorted array (does not mutate).
 * Returns `undefined` when the input is undefined (mirrors the original
 * useMemo's early-return contract).
 */
export function filterAndSortTours<T extends TourLike>(
  tours: T[] | undefined,
  { statusFilter, featuredFilter, searchKeyword, sortBy }: FilterOptions
): T[] | undefined {
  if (!tours) return undefined;
  return tours
    .filter((tour) => {
      if (statusFilter !== "all" && tour.status !== statusFilter) return false;
      if (featuredFilter === "featured" && tour.featured !== 1) return false;
      if (featuredFilter === "normal" && tour.featured === 1) return false;
      if (searchKeyword) {
        const keyword = searchKeyword.toLowerCase();
        return (
          tour.title.toLowerCase().includes(keyword) ||
          (tour.destination?.toLowerCase().includes(keyword) ?? false) ||
          (tour.destinationCountry?.toLowerCase().includes(keyword) ?? false) ||
          (tour.destinationCity?.toLowerCase().includes(keyword) ?? false)
        );
      }
      return true;
    })
    .sort((a, b) => {
      switch (sortBy) {
        case "price-asc":
          return a.price - b.price;
        case "price-desc":
          return b.price - a.price;
        case "duration-asc":
          return a.duration - b.duration;
        case "duration-desc":
          return b.duration - a.duration;
        case "date-asc":
          return (
            new Date(a.createdAt ?? 0).getTime() -
            new Date(b.createdAt ?? 0).getTime()
          );
        case "date-desc":
          return (
            new Date(b.createdAt ?? 0).getTime() -
            new Date(a.createdAt ?? 0).getTime()
          );
        default:
          return 0;
      }
    });
}

export interface ToursStats {
  active: number;
  draft: number;
  featured: number;
  recent: number;
}

/**
 * Stats for the 4-tile header. "recent" = created within the last 7 days.
 */
export function computeStats(tours: TourLike[] | undefined): ToursStats {
  if (!tours) return { active: 0, draft: 0, featured: 0, recent: 0 };
  const sevenDaysAgo = Date.now() - 7 * 24 * 60 * 60 * 1000;
  return {
    active: tours.filter((t) => t.status === "active").length,
    draft: tours.filter((t) => t.status !== "active").length,
    featured: tours.filter((t) => t.featured === 1).length,
    recent: tours.filter((t) => {
      const ts = t.createdAt ? new Date(t.createdAt).getTime() : 0;
      return ts >= sevenDaysAgo;
    }).length,
  };
}

export interface StatusCounts {
  all: number;
  active: number;
  inactive: number;
}

/**
 * Counts for the status-filter pills. "inactive" includes any non-active
 * status (matches the filter pill behavior).
 */
export function computeStatusCounts(
  tours: TourLike[] | undefined
): StatusCounts {
  if (!tours) return { all: 0, active: 0, inactive: 0 };
  return {
    all: tours.length,
    active: tours.filter((t) => t.status === "active").length,
    inactive: tours.filter((t) => t.status !== "active").length,
  };
}

/**
 * Map a Tour to the row data shape consumed by ToursTabRow / ToursTabCard.
 * `destination` falls back to empty string to satisfy TourRowData's
 * non-nullable contract — original inline code already did this implicitly
 * via the `(tour as any)` cast.
 *
 * NOTE: `status` is cast through `TourRowData["status"]` because the row
 * component currently only declares 3 status values while the underlying
 * tour may also be "draft" / "pending_review". This matches the original
 * inline mapper which used `(tour: any)` — broader typing of TourRowData
 * is a v2 task.
 */
export function toRowData(tour: TourLike): TourRowData {
  return {
    id: tour.id,
    title: tour.title,
    imageUrl: tour.imageUrl,
    destination: tour.destination ?? "",
    destinationCountry: tour.destinationCountry,
    destinationCity: tour.destinationCity,
    duration: tour.duration,
    price: tour.price,
    status: tour.status as TourRowData["status"],
    featured: tour.featured,
    isAutoGenerated: tour.isAutoGenerated,
    sourceUrl: tour.sourceUrl,
    calibrationVerdict: tour.calibrationVerdict,
    calibrationScore: tour.calibrationScore,
    hasAiDeparturePreview: !!tour.extractedDepartures,
  };
}
