/**
 * ToursTabAiGenerateDialog — AI 生成 modal (PDF / URL / PDF+URL).
 *
 * Round 80.10: pulled out of ToursTab.tsx verbatim. Visuals already cleaned
 * to B&W + gold in Round 80.9 — verified clean (no purple/blue).
 * Round 80.17: unified mode hint card (gold accent), PDF dropzone rounded-xl,
 * consistent gold active-tab text, button h-10 polish.
 */
import { useLocale } from "@/contexts/LocaleContext";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { GenerationProgressComponent } from "../GenerationProgress";
import {
  FileUp,
  Globe,
  Loader2,
  RefreshCw,
  Sparkles,
  Upload,
} from "lucide-react";

// v80.24: removed "pdf_url" mixed mode; PDF + auto-supplemented URL is no
// longer needed per Jeff's request — keep type union flexible for callers.
type InputMode = "url" | "pdf" | "pdf_url";

interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  inputMode: InputMode;
  setInputMode: (m: InputMode) => void;
  autoGenerateUrl: string;
  setAutoGenerateUrl: (v: string) => void;
  supplementUrl: string;
  setSupplementUrl: (v: string) => void;
  pdfFile: File | null;
  setPdfFile: (f: File | null) => void;
  forceRegenerate: boolean;
  setForceRegenerate: (v: boolean) => void;
  isGenerating: boolean;
  pdfUploading: boolean;
  currentTaskId: string | null;
  generationStatus: any;
  generationError: string | null;
  setGenerationError: (v: string | null) => void;
  isPending: boolean;
  onGenerate: () => void;
  onClose: () => void;
}

export function ToursTabAiGenerateDialog({
  open,
  onOpenChange,
  inputMode,
  setInputMode,
  autoGenerateUrl,
  setAutoGenerateUrl,
  supplementUrl,
  setSupplementUrl,
  pdfFile,
  setPdfFile,
  forceRegenerate,
  setForceRegenerate,
  isGenerating,
  pdfUploading,
  currentTaskId,
  generationStatus,
  generationError,
  setGenerationError,
  isPending,
  onGenerate,
  onClose,
}: Props) {
  const { t } = useLocale();

  return (
    <Dialog
      open={open}
      onOpenChange={(o) => {
        if (!o) onClose();
        else onOpenChange(true);
      }}
    >
      <DialogContent className="max-w-lg rounded-xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-[#c9a563]" />
            {t("toursTab.aiAutoGenerateTitle")}
          </DialogTitle>
          <DialogDescription>
            {t("toursTab.aiAutoGenerateDesc")}
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-4 py-4">
          {/* Input mode tabs — v80.24: removed PDF+URL mixed mode (Jeff dropped
              the feature; redundant with PDF-only + auto-supplement). */}
          <div className="flex gap-1 p-1 bg-gray-100 rounded-lg">
            <button
              type="button"
              onClick={() => setInputMode("pdf")}
              disabled={isGenerating || pdfUploading}
              className={`flex-1 flex items-center justify-center gap-1.5 py-2 px-2 rounded-md text-xs font-medium transition-all ${
                inputMode === "pdf"
                  ? "bg-white text-foreground shadow-sm"
                  : "text-gray-600 hover:text-foreground"
              }`}
            >
              <FileUp className="h-3.5 w-3.5" />
              {t("toursTab.modePdf")}
            </button>
            <button
              type="button"
              onClick={() => setInputMode("url")}
              disabled={isGenerating || pdfUploading}
              className={`flex-1 flex items-center justify-center gap-1.5 py-2 px-2 rounded-md text-xs font-medium transition-all ${
                inputMode === "url"
                  ? "bg-white text-foreground shadow-sm"
                  : "text-gray-600 hover:text-foreground"
              }`}
            >
              <Globe className="h-3.5 w-3.5" />
              {t("toursTab.modeUrl")}
            </button>
          </div>

          <div className="text-xs rounded-lg px-3 py-2 bg-[#FAF8F2] border border-[#c9a563]/30 text-foreground/70">
            {inputMode === "pdf" && t("toursTab.modePdfHint")}
            {inputMode === "url" && t("toursTab.modeUrlHint")}
          </div>

          {inputMode === "url" && (
            <div className="space-y-2">
              <Label className="text-sm font-medium">
                {t("toursTab.urlInputLabel")}
              </Label>
              <input
                type="url"
                value={autoGenerateUrl}
                onChange={(e) => setAutoGenerateUrl(e.target.value)}
                placeholder="https://travel.liontravel.com/detail?..."
                disabled={isGenerating}
                className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-foreground/20 focus:border-foreground/40"
              />
            </div>
          )}

          {inputMode === "pdf" && (
            <div className="space-y-2">
              <Label>{t("toursTab.selectPdfFile")}</Label>
              <div
                className={`border-2 border-dashed rounded-xl p-8 text-center transition-colors ${
                  pdfFile
                    ? "border-[#c9a563] bg-[#c9a563]/5"
                    : "border-gray-300 hover:border-[#c9a563] hover:bg-[#c9a563]/5"
                }`}
              >
                <input
                  type="file"
                  accept=".pdf,application/pdf"
                  onChange={(e) => {
                    const file = e.target.files?.[0];
                    if (file) setPdfFile(file);
                  }}
                  disabled={isGenerating || pdfUploading}
                  className="hidden"
                  id="pdf-upload"
                />
                <label
                  htmlFor="pdf-upload"
                  className="cursor-pointer flex flex-col items-center gap-2"
                >
                  {pdfFile ? (
                    <>
                      <FileUp className="h-8 w-8 text-[#8a6f3a]" />
                      <span className="text-sm font-medium text-[#8a6f3a]">
                        {pdfFile.name}
                      </span>
                      <span className="text-xs text-gray-500">
                        {(pdfFile.size / 1024 / 1024).toFixed(2)} MB
                      </span>
                    </>
                  ) : (
                    <>
                      <Upload className="h-8 w-8 text-gray-400" />
                      <span className="text-sm text-gray-600">
                        {t("toursTab.dropPdfHint")}
                      </span>
                      <span className="text-xs text-gray-400">
                        {t("toursTab.pdfSupportHint")}
                      </span>
                    </>
                  )}
                </label>
              </div>
              {pdfFile && (
                <button
                  type="button"
                  onClick={() => setPdfFile(null)}
                  className="text-xs text-red-500 hover:text-red-700"
                >
                  {t("toursTab.clearFile")}
                </button>
              )}
            </div>
          )}

          {/* v80.24: pdf_url supplementUrl block removed */}

          <div className="flex items-center space-x-2">
            <input
              type="checkbox"
              id="forceRegenerate"
              checked={forceRegenerate}
              onChange={(e) => setForceRegenerate(e.target.checked)}
              disabled={isPending || isGenerating}
              className="h-4 w-4 rounded border-gray-300 text-foreground focus:ring-foreground"
            />
            <Label
              htmlFor="forceRegenerate"
              className="text-sm font-normal cursor-pointer"
            >
              {t("toursTab.forceRegenerate")}
            </Label>
          </div>

          {isGenerating && (
            <GenerationProgressComponent
              taskId={currentTaskId}
              isGenerating={isGenerating}
              pollingStatus={generationStatus}
              onComplete={() => {
                /* parent handles via polling */
              }}
              onError={() => {
                /* parent handles via polling */
              }}
            />
          )}

          {generationError && !isGenerating && (
            <div className="mt-3 p-4 bg-red-50 border border-red-200 rounded-lg">
              <div className="flex items-start gap-3">
                <div className="flex-shrink-0 w-8 h-8 bg-red-100 rounded-full flex items-center justify-center">
                  <svg
                    className="w-4 h-4 text-red-600"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M6 18L18 6M6 6l12 12"
                    />
                  </svg>
                </div>
                <div className="flex-1 min-w-0">
                  <h4 className="text-sm font-semibold text-red-800">
                    {t("toursTab.generationFailed")}
                  </h4>
                  <p className="text-xs text-red-600 mt-1">
                    {t("toursTab.generationFailedDesc")}
                  </p>
                  <details className="mt-2">
                    <summary className="text-xs text-red-500 cursor-pointer hover:text-red-700">
                      {t("toursTab.errorDetails")}
                    </summary>
                    <p className="text-xs text-red-500 mt-1 font-mono break-all">
                      {generationError}
                    </p>
                  </details>
                </div>
              </div>
            </div>
          )}
        </div>
        <DialogFooter>
          {generationError && !isGenerating ? (
            <>
              <Button
                variant="outline"
                onClick={() => setGenerationError(null)}
                className="rounded-lg"
              >
                {t("toursTab.backToInput")}
              </Button>
              <Button
                onClick={() => {
                  setGenerationError(null);
                  onGenerate();
                }}
                className="bg-foreground text-white hover:bg-foreground/85 rounded-lg"
              >
                <RefreshCw className="h-4 w-4 mr-2" />
                {t("toursTab.retryGeneration")}
              </Button>
            </>
          ) : (
            <>
              <Button
                variant="outline"
                onClick={onClose}
                className="rounded-lg"
              >
                {isGenerating
                  ? t("toursTab.minimizeToBackground") || "縮小到背景"
                  : t("common.cancel")}
              </Button>
              <Button
                onClick={onGenerate}
                disabled={
                  isPending ||
                  isGenerating ||
                  pdfUploading ||
                  (inputMode === "url"
                    ? !autoGenerateUrl.trim()
                    : !pdfFile)
                }
                className="bg-foreground text-white hover:bg-foreground/85 rounded-lg h-10 px-5 disabled:opacity-60"
              >
                {isPending || isGenerating || pdfUploading ? (
                  <>
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                    {t("toursTab.generating")}
                  </>
                ) : (
                  <>
                    <Sparkles className="h-4 w-4 mr-2 text-[#c9a563]" />
                    {t("toursTab.startGenerate")}
                  </>
                )}
              </Button>
            </>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
