/**
 * ToursTabCard — single tour card in grid view.
 *
 * Round 80.10 redesign: image-forward card with inline checkbox + featured
 * star overlay. Same actions as the row, just rearranged.
 */
import { useLocale } from "@/contexts/LocaleContext";
import { currencySymbol, type SupportedCurrency } from "@/lib/currency";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Calendar,
  Check,
  Copy,
  Edit,
  Eye,
  EyeOff,
  MoreHorizontal,
  Sparkles,
  Star,
  Trash2,
} from "lucide-react";
import type { TourRowData } from "./ToursTabRow";

interface ToursTabCardProps {
  tour: TourRowData;
  isSelected: boolean;
  onToggleSelect: () => void;
  onEdit: () => void;
  onToggleStatus: () => void;
  onToggleFeatured: () => void;
  onManageDepartures: () => void;
  onAiDeparturePreview: () => void;
  onDuplicate: () => void;
  onDelete: () => void;
  toggleStatusPending?: boolean;
  toggleFeaturedPending?: boolean;
  duplicatePending?: boolean;
}

export function ToursTabCard({
  tour,
  isSelected,
  onToggleSelect,
  onEdit,
  onToggleStatus,
  onToggleFeatured,
  onManageDepartures,
  onAiDeparturePreview,
  onDuplicate,
  onDelete,
  toggleStatusPending,
  toggleFeaturedPending,
  duplicatePending,
}: ToursTabCardProps) {
  const { t } = useLocale();
  const isFeatured = tour.featured === 1;
  const isActive = tour.status === "active";
  const isAi = tour.isAutoGenerated === 1;

  return (
    <div
      className={`bg-white border-2 rounded-xl overflow-hidden transition-colors ${
        isSelected ? "border-[#c9a563]" : "border-gray-200 hover:border-gray-300"
      }`}
    >
      <div className="relative">
        {tour.imageUrl ? (
          <img
            src={tour.imageUrl}
            alt={tour.title}
            className="w-full h-40 object-cover"
          />
        ) : (
          <div className="w-full h-40 bg-gray-100 flex items-center justify-center">
            <span className="text-gray-400 text-xs">
              {t("toursTab.noImage")}
            </span>
          </div>
        )}
        <div className="absolute top-2 right-2 flex gap-1">
          <button
            type="button"
            disabled={toggleFeaturedPending}
            onClick={onToggleFeatured}
            title={
              isFeatured
                ? t("toursTab.removeFeatured")
                : t("toursTab.setFeatured")
            }
            className="p-1.5 bg-white/90 backdrop-blur rounded-lg hover:bg-white transition-colors disabled:opacity-50"
          >
            <Star
              className={`w-4 h-4 ${
                isFeatured
                  ? "fill-[#c9a563] text-[#c9a563]"
                  : "text-gray-400"
              }`}
            />
          </button>
          <button
            type="button"
            disabled={toggleStatusPending}
            onClick={onToggleStatus}
            title={isActive ? t("toursTab.deactivate") : t("toursTab.activate")}
            className="p-1.5 bg-white/90 backdrop-blur rounded-lg hover:bg-white transition-colors text-gray-600 disabled:opacity-50"
          >
            {isActive ? (
              <Eye className="w-4 h-4" />
            ) : (
              <EyeOff className="w-4 h-4" />
            )}
          </button>
        </div>
        <button
          type="button"
          onClick={onToggleSelect}
          aria-label={t("toursTab.selectTour")}
          className="absolute top-2 left-2 w-5 h-5 rounded border-2 bg-white/90 backdrop-blur hover:bg-white transition-colors flex items-center justify-center"
          style={
            isSelected
              ? {
                  background: "var(--foreground)",
                  borderColor: "var(--foreground)",
                }
              : { borderColor: "rgba(0,0,0,0.2)" }
          }
        >
          {isSelected && <Check className="w-3 h-3 text-white" />}
        </button>
        {isAi && (
          <span className="absolute bottom-2 left-2 inline-flex items-center gap-1 text-[10px] uppercase tracking-wider font-bold text-[#8a6f3a] bg-white/90 backdrop-blur px-2 py-1 rounded-md">
            <Sparkles className="w-2.5 h-2.5" />
            AI
            {tour.calibrationScore != null && ` · QA ${tour.calibrationScore}`}
          </span>
        )}
        {!isActive && (
          <span className="absolute bottom-2 right-2 inline-flex items-center text-[10px] uppercase tracking-wider font-medium px-2 py-1 rounded-md bg-gray-900/85 text-white backdrop-blur">
            {t("toursTab.statusInactiveBadge")}
          </span>
        )}
      </div>
      <div className="p-4">
        <p className="text-sm font-semibold text-foreground line-clamp-2 leading-snug mb-2 min-h-[40px]">
          {tour.title}
        </p>
        <div className="flex items-center gap-2 text-xs text-gray-500 mb-3">
          <span>
            {tour.destinationCountry || tour.destination}
            {tour.destinationCity ? ` · ${tour.destinationCity}` : ""}
          </span>
          <span>·</span>
          <span>{t("toursTab.daysUnit").replace("{days}", String(tour.duration))}</span>
        </div>
        <div className="flex items-center justify-between pt-3 border-t border-gray-100">
          <span className="text-base font-bold text-foreground tabular-nums">
            {currencySymbol((tour.priceCurrency || "TWD") as SupportedCurrency)} {tour.price.toLocaleString()}
          </span>
          <div className="flex items-center gap-1">
            <Button
              variant="ghost"
              size="sm"
              onClick={onEdit}
              className="px-3 h-8 text-xs font-medium text-foreground border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors flex items-center gap-1.5"
            >
              <Edit className="w-3.5 h-3.5" />
              {t("toursTab.editButton")}
            </Button>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <button
                  type="button"
                  title={t("toursTab.moreActions")}
                  className="p-1.5 rounded-lg hover:bg-gray-100 transition-colors text-gray-500 hover:text-foreground"
                >
                  <MoreHorizontal className="w-4 h-4" />
                </button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end" className="w-48 rounded-lg">
                <DropdownMenuItem
                  onClick={onManageDepartures}
                  className="cursor-pointer"
                >
                  <Calendar className="h-4 w-4 mr-2 text-gray-500" />
                  {t("toursTab.manageDepartures")}
                </DropdownMenuItem>
                {tour.hasAiDeparturePreview && (
                  <DropdownMenuItem
                    onClick={onAiDeparturePreview}
                    className="cursor-pointer text-[#8a6f3a] focus:text-[#8a6f3a] focus:bg-[#c9a563]/10"
                  >
                    <Sparkles className="h-4 w-4 mr-2 text-[#c9a563]" />
                    {t("toursTab.aiDeparturePreview")}
                  </DropdownMenuItem>
                )}
                <DropdownMenuSeparator />
                <DropdownMenuItem
                  onClick={onDuplicate}
                  disabled={duplicatePending}
                  className="cursor-pointer"
                >
                  <Copy className="h-4 w-4 mr-2 text-gray-500" />
                  {t("toursTab.copyTour")}
                </DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem
                  onClick={onDelete}
                  className="cursor-pointer text-red-600 focus:text-red-600 focus:bg-red-50"
                >
                  <Trash2 className="h-4 w-4 mr-2" />
                  {t("toursTab.deleteTour")}
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>
      </div>
    </div>
  );
}
