/**
 * ToursTabRow — single tour row in list view.
 *
 * Round 80.10 redesign:
 * - Thumbnail (rounded-lg) + title (line-clamp-1) + chip row
 * - Inline ★ featured toggle + 👁 status toggle (1-click, no dropdown)
 * - 編輯 button + ⋯ more menu (dates, duplicate, delete, AI departure preview)
 * - Removes the category pill (90% of inventory is "group", not informative)
 *
 * Brand baseline (CLAUDE.md): rounded-xl/lg/md only, no purple/blue/etc.
 */
import { useLocale } from "@/contexts/LocaleContext";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Calendar,
  Copy,
  Edit,
  ExternalLink,
  Eye,
  EyeOff,
  MoreHorizontal,
  Sparkles,
  Star,
  Trash2,
  Check,
} from "lucide-react";

export interface TourRowData {
  id: number;
  title: string;
  imageUrl?: string | null;
  destination: string;
  destinationCountry?: string | null;
  destinationCity?: string | null;
  duration: number;
  price: number;
  status: "active" | "inactive" | "soldout";
  featured: number | null;
  isAutoGenerated?: number | null;
  sourceUrl?: string | null;
  calibrationVerdict?: string | null;
  calibrationScore?: number | null;
  hasAiDeparturePreview?: boolean;
}

interface ToursTabRowProps {
  tour: TourRowData;
  isSelected: boolean;
  onToggleSelect: () => void;
  onEdit: () => void;
  onToggleStatus: () => void;
  onToggleFeatured: () => void;
  onManageDepartures: () => void;
  onAiDeparturePreview: () => void;
  onDuplicate: () => void;
  onDelete: () => void;
  toggleStatusPending?: boolean;
  toggleFeaturedPending?: boolean;
  duplicatePending?: boolean;
}

export function ToursTabRow({
  tour,
  isSelected,
  onToggleSelect,
  onEdit,
  onToggleStatus,
  onToggleFeatured,
  onManageDepartures,
  onAiDeparturePreview,
  onDuplicate,
  onDelete,
  toggleStatusPending,
  toggleFeaturedPending,
  duplicatePending,
}: ToursTabRowProps) {
  const { t } = useLocale();
  const isFeatured = tour.featured === 1;
  const isActive = tour.status === "active";
  const isAi = tour.isAutoGenerated === 1;

  const verdict = tour.calibrationVerdict;
  const isApproved = verdict === "approved" || verdict === "pass";
  const isReview = verdict === "review" || verdict === "warn";

  return (
    <div
      className={`flex items-center gap-4 p-4 transition-colors ${
        isSelected ? "bg-[#c9a563]/5" : "hover:bg-gray-50"
      }`}
    >
      {/* Checkbox */}
      <button
        type="button"
        onClick={onToggleSelect}
        aria-label={t("toursTab.selectTour")}
        className="flex-shrink-0 w-5 h-5 rounded border-2 border-gray-300 hover:border-foreground transition-colors flex items-center justify-center"
        style={
          isSelected
            ? { background: "var(--foreground)", borderColor: "var(--foreground)" }
            : {}
        }
      >
        {isSelected && <Check className="w-3 h-3 text-white" />}
      </button>

      {/* Thumbnail */}
      {tour.imageUrl ? (
        <img
          src={tour.imageUrl}
          alt={tour.title}
          className="w-20 h-14 object-cover rounded-lg flex-shrink-0"
        />
      ) : (
        <div className="w-20 h-14 bg-gray-100 rounded-lg flex items-center justify-center flex-shrink-0">
          <span className="text-gray-400 text-[10px]">
            {t("toursTab.noImage")}
          </span>
        </div>
      )}

      {/* Title + meta */}
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2 mb-1 flex-wrap">
          {isAi && (
            <span className="inline-flex items-center gap-1 text-[10px] uppercase tracking-wider font-bold text-[#8a6f3a] bg-[#c9a563]/10 px-1.5 py-0.5 rounded-md">
              <Sparkles className="w-2.5 h-2.5" />
              AI
              {tour.calibrationScore != null && (
                <span className="ml-0.5">QA {tour.calibrationScore}</span>
              )}
            </span>
          )}
          <span
            className={`inline-flex items-center text-[10px] uppercase tracking-wider font-medium px-1.5 py-0.5 rounded-md ${
              isActive
                ? "bg-foreground/5 text-foreground"
                : "bg-gray-100 text-gray-500"
            }`}
          >
            {isActive
              ? t("toursTab.statusActiveBadge")
              : t("toursTab.statusInactiveBadge")}
          </span>
          {isFeatured && (
            <span className="inline-flex items-center gap-0.5 text-[10px] uppercase tracking-wider font-bold text-[#8a6f3a] bg-[#c9a563]/10 px-1.5 py-0.5 rounded-md">
              <Star className="w-2.5 h-2.5 fill-current" />
              {t("toursTab.featuredBadgeShort")}
            </span>
          )}
          {isAi && verdict && (
            <span
              className={`inline-flex items-center text-[10px] font-medium px-1.5 py-0.5 rounded-md ${
                isApproved
                  ? "bg-foreground/5 text-foreground/70"
                  : isReview
                  ? "bg-[#c9a563]/10 text-[#8a6f3a]"
                  : "bg-red-50 text-red-700"
              }`}
              title={t("toursTab.calibrationScoreTitle").replace(
                "{score}",
                String(tour.calibrationScore ?? "-")
              )}
            >
              {isApproved ? "✓" : isReview ? "!" : "×"} {verdict}
            </span>
          )}
          {isAi && tour.sourceUrl && (
            <a
              href={tour.sourceUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1 text-[10px] text-foreground/60 hover:text-[#c9a563] hover:underline transition-colors"
              title={t("toursTab.viewSource")}
              onClick={(e) => e.stopPropagation()}
            >
              <ExternalLink className="w-2.5 h-2.5" />
              {t("toursTab.originalLink")}
            </a>
          )}
        </div>
        <p className="text-sm font-semibold text-foreground line-clamp-1">
          {tour.title}
        </p>
        <div className="flex items-center gap-2 mt-1 text-xs text-gray-500 flex-wrap">
          <span>
            {tour.destinationCountry || tour.destination}
            {tour.destinationCity ? ` · ${tour.destinationCity}` : ""}
          </span>
          <span>·</span>
          <span>{t("toursTab.daysUnit").replace("{days}", String(tour.duration))}</span>
          <span>·</span>
          <span className="font-semibold text-foreground tabular-nums">
            NT$ {tour.price.toLocaleString()}
          </span>
        </div>
      </div>

      {/* Inline actions */}
      <div className="flex items-center gap-1 flex-shrink-0">
        <button
          type="button"
          title={
            isFeatured
              ? t("toursTab.removeFeatured")
              : t("toursTab.setFeatured")
          }
          disabled={toggleFeaturedPending}
          onClick={onToggleFeatured}
          className={`p-1.5 rounded-lg hover:bg-gray-100 transition-colors disabled:opacity-50 ${
            isFeatured ? "text-[#c9a563]" : "text-gray-300 hover:text-gray-500"
          }`}
        >
          <Star className={`w-4 h-4 ${isFeatured ? "fill-current" : ""}`} />
        </button>
        <button
          type="button"
          title={isActive ? t("toursTab.deactivate") : t("toursTab.activate")}
          disabled={toggleStatusPending}
          onClick={onToggleStatus}
          className="p-1.5 rounded-lg hover:bg-gray-100 transition-colors text-gray-500 hover:text-foreground disabled:opacity-50"
        >
          {isActive ? <Eye className="w-4 h-4" /> : <EyeOff className="w-4 h-4" />}
        </button>
        <div className="w-px h-5 bg-gray-200 mx-1" />
        <Button
          variant="ghost"
          size="sm"
          onClick={onEdit}
          className="px-3 h-8 text-xs font-medium text-foreground border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors flex items-center gap-1.5"
        >
          <Edit className="w-3.5 h-3.5" />
          {t("toursTab.editButton")}
        </Button>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <button
              type="button"
              title={t("toursTab.moreActions")}
              className="p-1.5 rounded-lg hover:bg-gray-100 transition-colors text-gray-500 hover:text-foreground"
            >
              <MoreHorizontal className="w-4 h-4" />
            </button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end" className="w-48 rounded-lg">
            <DropdownMenuItem
              onClick={onManageDepartures}
              className="cursor-pointer"
            >
              <Calendar className="h-4 w-4 mr-2 text-gray-500" />
              {t("toursTab.manageDepartures")}
            </DropdownMenuItem>
            {tour.hasAiDeparturePreview && (
              <DropdownMenuItem
                onClick={onAiDeparturePreview}
                className="cursor-pointer text-[#8a6f3a] focus:text-[#8a6f3a] focus:bg-[#c9a563]/10"
              >
                <Sparkles className="h-4 w-4 mr-2 text-[#c9a563]" />
                {t("toursTab.aiDeparturePreview")}
              </DropdownMenuItem>
            )}
            <DropdownMenuSeparator />
            <DropdownMenuItem
              onClick={onDuplicate}
              disabled={duplicatePending}
              className="cursor-pointer"
            >
              <Copy className="h-4 w-4 mr-2 text-gray-500" />
              {t("toursTab.copyTour")}
            </DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem
              onClick={onDelete}
              className="cursor-pointer text-red-600 focus:text-red-600 focus:bg-red-50"
            >
              <Trash2 className="h-4 w-4 mr-2" />
              {t("toursTab.deleteTour")}
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>
    </div>
  );
}
