/**
 * registryWhitelist.ts — C 類白名單:server/ 裡「不進 EXPLAIN 彩排」的 raw SQL 出現點。
 * 每條寫明理由。coverage.test.ts:每個 source 要嘛在此、要嘛在 ENTRIES.sources。
 */
import type { WhitelistEntry } from "./registry";

export const WHITELIST: WhitelistEntry[] = [
  { source: "server/_core/healthCheck.ts:161", reason: "SELECT 1 是純健康探測(liveness ping),不含任何表/欄位,不對應任何 schema 查詢,EXPLAIN 對它無意義(MySQL/TiDB 對 SELECT 1 的 EXPLAIN 只會顯示 'No tables used',沒有計畫可彩排)。" },
  { source: "server/_core/guestNoiseGate.ts:86", reason: "可重用 SQL 片段常量(qualifiesViaContent 之類 EXISTS(...) 片段),本身非獨立語句無法單獨 EXPLAIN;其 parse 由呼叫端 adminCustomers.buildGuestListQuery / runGuestUnreadRankingQuery 與 globalSearch.* 的已登記查詢覆蓋。" },
  { source: "server/_core/guestNoiseGate.ts:93", reason: "可重用 SQL 片段常量(latestInboundIsSpam 之類子查詢片段),本身非獨立語句;其 parse 由呼叫端 globalSearch.* / adminCustomers.* 的已登記查詢覆蓋。" },
  // ── gmail-intake-ledger 新表首航(0117 gmailIngestionLedger,prod 尚未套用)────
  // TODO(0117 上 prod 後):把下面四條移入 registryEntries 正式登記(裸語句見各條 reason),
  // 從白名單刪除。追蹤:docs/features/gmail-intake-ledger/progress.md。
  // 行號隨 Codex 16 輪 P0(事件級冪等 + row claim)改動而更新(202→217, 240→258, 348→416,
  // 新增 271 的嚴格大於重排閘門)。
  { source: "server/services/gmailIntakeAdapters.ts:217", reason: "新表首航:gmailIngestionLedger 由 migration 0117 建立,prod TiDB 尚未套用(migration 在 release_command 才跑,閘 6.5 的 EXPLAIN 在部署前執行),對不存在的表 EXPLAIN 必然 resolution 失敗,登記反而永紅 —— 無既有新表先例(0116 checkoutDisclosures / 0079 skillRuns 批皆無 raw SQL token)。0117 套用後移入正式登記。v4(Codex 16 輪 P0-2 事件級冪等)發現寫入的 statement 1:最小發現列 insert,drizzle 對 .values() 每值綁參(含常量 internalDateMs=0 / status='pending' / discoveryReason='initial';多列一次 insert 時 VALUES 元組逐列重複),gmailHistoryId+lastSeenHistoryId 落每事件 record id,ON DUPLICATE KEY 把 lastSeenHistoryId 改為 FORWARD-ONLY(CAST UNSIGNED 大數比較,NULL-safe 雙向):INSERT INTO `gmailIngestionLedger` (`integrationId`,`gmailMessageId`,`gmailThreadId`,`gmailHistoryId`,`lastSeenHistoryId`,`discoveryReason`,`internalDateMs`,`source`,`status`) VALUES (?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE `lastSeenHistoryId` = case when values(`lastSeenHistoryId`) is null then `lastSeenHistoryId` when `lastSeenHistoryId` is null then values(`lastSeenHistoryId`) when cast(values(`lastSeenHistoryId`) as unsigned) > cast(`lastSeenHistoryId` as unsigned) then values(`lastSeenHistoryId`) else `lastSeenHistoryId` end,sampleParams 每列 [1,'m1','t1','H2','H2','initial',0,'history','pending'](cls B,sql`case ... end` 為 ODKU 片段)。" },
  { source: "server/services/gmailIntakeAdapters.ts:258", reason: "新表首航:同上,gmailIngestionLedger(0117)prod 尚未存在,EXPLAIN 不可行;0117 套用後移入正式登記。v4(Codex 16 輪 P0-2)requeue 改為 PER-MESSAGE 條件式 CAS(每候選各帶自己的 eventHistoryId,逐列 UPDATE):把 status='ignored' 的列翻回 pending 重新分類並記稽核(requeueCount+1),清 claim 欄,SET 無任何欄引用 status 故無 ODKU 賦值順序雷(見 271 的嚴格大於閘門):UPDATE `gmailIngestionLedger` SET `status` = ?,`route` = ?,`wouldRoute` = ?,`classifiedAt` = ?,`fromAddress` = ?,`internalDateMs` = ?,`failureKind` = ?,`errorDetail` = ?,`httpStatus` = ?,`retryCount` = ?,`nextRetryAt` = ?,`processedAt` = ?,`interactionId` = ?,`discoveryReason` = ?,`lastRequeuedAt` = ?,`requeueCount` = `requeueCount` + 1,`lastRequeueEventId` = ?,`claimToken` = ?,`claimExpiresAt` = ?,`claimStage` = ? WHERE (`integrationId` = ? AND `gmailMessageId` = ? AND `status` = ? AND (`lastRequeueEventId` is null or cast(? as unsigned) > cast(`lastRequeueEventId` as unsigned))),sampleParams ['pending',null,null,null,null,0,null,null,null,0,null,null,null,'inbox_requeue',NOW(),'9007199254740999',null,null,null,1,'m1','ignored','9007199254740999'](cls B,sql`requeueCount + 1` 為自增片段)。" },
  { source: "server/services/gmailIntakeAdapters.ts:271", reason: "新表首航:同上,0117 尚未套用,EXPLAIN 不可行。v4(Codex 16 輪 P0-2 事件級重排冪等)requeue 的 WHERE 嚴格大於閘門片段(併入 258 的整條 UPDATE 一起彩排):只有本 label 事件的 record id 嚴格大於本列 lastRequeueEventId 才重排,replay 同一/較舊事件 affectedRows=0 不重複累加。裸語句同 258 條(此 token 是該 UPDATE 的 WHERE 子片段):`lastRequeueEventId` is null or cast(? as unsigned) > cast(`lastRequeueEventId` as unsigned),sampleParams ['9007199254740999'](cls B,BigInt-precise CAST UNSIGNED 比較,避免字面大於 2^53 的字典序/Number 陷阱)。" },
  { source: "server/services/gmailIntakeAdapters.ts:419", reason: "新表首航:同上,0117 尚未套用,EXPLAIN 不可行;0117 套用後移入正式登記(行號 416→419:對抗審查修正在 claimActionable 前補了誠實註解)。v4(Codex 16 輪 P0-3)claimActionable 的 CAS claim WHERE 片段(feeder 只搶已分類 customer/receipt pending 加重試到期 failed、且 lease 空閒的列):UPDATE `gmailIngestionLedger` SET `claimToken` = ?,`claimExpiresAt` = ?,`claimStage` = ? WHERE (`integrationId` = ? AND ((`status` = ? AND `route` IN (?, ?)) OR (`status` = ? AND `retryCount` <= ? AND `nextRetryAt` IS NOT NULL AND `nextRetryAt` <= ?)) AND (`claimToken` IS NULL OR `claimExpiresAt` <= ?)) ORDER BY `firstSeenAt` ASC LIMIT ?,sampleParams ['tok',NOW(),'feed',1,'pending','customer','receipt','failed',2,NOW(),NOW(),100](cls B,sql`nextRetryAt IS NOT NULL` 為片段)。註:advanceCursorCAS、claimUnclassified / renewClaim / releaseClaim / recordClassifyFailure / classify / markProcessed / markIgnored / markFailed 的 token-gated UPDATE、statement-2 requeue 其餘欄,均純 drizzle builder,除上列四個 raw token 外無其他 sql`` 出現點,不在盤點口徑內。" },
];
