/**
 * registryWhitelist.ts — C 類白名單:server/ 裡「不進 EXPLAIN 彩排」的 raw SQL 出現點。
 * 每條寫明理由。coverage.test.ts:每個 source 要嘛在此、要嘛在 ENTRIES.sources。
 */
import type { WhitelistEntry } from "./registry";

export const WHITELIST: WhitelistEntry[] = [
  { source: "server/_core/healthCheck.ts:161", reason: "SELECT 1 是純健康探測(liveness ping),不含任何表/欄位,不對應任何 schema 查詢,EXPLAIN 對它無意義(MySQL/TiDB 對 SELECT 1 的 EXPLAIN 只會顯示 'No tables used',沒有計畫可彩排)。" },
  { source: "server/_core/guestNoiseGate.ts:86", reason: "可重用 SQL 片段常量(qualifiesViaContent 之類 EXISTS(...) 片段),本身非獨立語句無法單獨 EXPLAIN;其 parse 由呼叫端 adminCustomers.buildGuestListQuery / runGuestUnreadRankingQuery 與 globalSearch.* 的已登記查詢覆蓋。" },
  { source: "server/_core/guestNoiseGate.ts:93", reason: "可重用 SQL 片段常量(latestInboundIsSpam 之類子查詢片段),本身非獨立語句;其 parse 由呼叫端 globalSearch.* / adminCustomers.* 的已登記查詢覆蓋。" },
  // ── gmail-intake-ledger 新表首航(0117 gmailIngestionLedger,prod 尚未套用)────
  // TODO(0117 上 prod 後):把下面五條移入 registryEntries 正式登記(裸語句見各條 reason),
  // 從白名單刪除。追蹤:docs/features/gmail-intake-ledger/progress.md。
  // 行號隨 Codex 18 輪 §四/§七(三值 MAX 消耗水位 + scan floor)改動而更新:requeue 的 WHERE
  // 閘由 COALESCE(lastRequeueEventId, lastSeenHistoryId) 升為嚴格大於三值數值
  // MAX(lastRequeueEventId, lastSeenHistoryId, scanConsumedFloor)(NULL-safe GREATEST-COALESCE);
  // statement-2 INSERT 加 scanConsumedFloor 欄(scan/bootstrap 建列持久寫掃描前 baseline,
  // history/ODKU 不碰)。行號(Codex 17→18):235→238(requeueCount+1)、241→244(requeue lastSeen
  // GREATEST)、253→267(WHERE 三值 MAX 閘)、288→308(INSERT ODKU + scanConsumedFloor 欄)、
  // 436→456(claimActionable)。
  { source: "server/services/gmailIntakeAdapters.ts:238", reason: "新表首航:gmailIngestionLedger 由 migration 0117 建立,prod TiDB 尚未套用(migration 在 release_command 才跑,閘 6.5 的 EXPLAIN 在部署前執行),對不存在的表 EXPLAIN 必然 resolution 失敗,登記反而永紅 —— 無既有新表先例(0116 checkoutDisclosures / 0079 skillRuns 批皆無 raw SQL token)。0117 套用後移入正式登記。v5(Codex 17 輪 §四 事件消耗水位)requeue 改為 statement 1(先於 INSERT 跑,讀本事件之前的水位),PER-MESSAGE 條件式 CAS(每候選各帶自己的 labelEventId,逐列 UPDATE):把 status='ignored' 的列翻回 pending 重新分類並記稽核(requeueCount+1),同一 UPDATE 內原子完成「記消耗 lastRequeueEventId + 單調推進 lastSeenHistoryId」(見 244)且清 claim 欄(scanConsumedFloor 為永久掃描 baseline,requeue 不碰),SET 無任何欄引用 status 故無賦值順序雷(見 267 的三值 MAX 消耗水位閘門):UPDATE `gmailIngestionLedger` SET `status` = ?,`route` = ?,`wouldRoute` = ?,`classifiedAt` = ?,`fromAddress` = ?,`internalDateMs` = ?,`failureKind` = ?,`errorDetail` = ?,`httpStatus` = ?,`retryCount` = ?,`nextRetryAt` = ?,`processedAt` = ?,`interactionId` = ?,`discoveryReason` = ?,`lastRequeuedAt` = ?,`requeueCount` = `requeueCount` + 1,`lastRequeueEventId` = ?,`lastSeenHistoryId` = case when `lastSeenHistoryId` is null then ? when ? is null then `lastSeenHistoryId` when cast(? as unsigned) > cast(`lastSeenHistoryId` as unsigned) then ? else `lastSeenHistoryId` end,`claimToken` = ?,`claimExpiresAt` = ?,`claimStage` = ? WHERE (`integrationId` = ? AND `gmailMessageId` = ? AND `status` = ? AND cast(? as unsigned) > greatest(coalesce(cast(`lastRequeueEventId` as unsigned), cast(`lastSeenHistoryId` as unsigned), cast(`scanConsumedFloor` as unsigned)), coalesce(cast(`lastSeenHistoryId` as unsigned), cast(`scanConsumedFloor` as unsigned), cast(`lastRequeueEventId` as unsigned)), coalesce(cast(`scanConsumedFloor` as unsigned), cast(`lastRequeueEventId` as unsigned), cast(`lastSeenHistoryId` as unsigned)))),sampleParams ['pending',null,null,null,null,0,null,null,null,0,null,null,null,'inbox_requeue',NOW(),'9007199254740999','9007199254740999','9007199254740999','9007199254740999','9007199254740999',null,null,null,1,'m1','ignored','9007199254740999'](cls B,sql`requeueCount + 1` 為自增片段)。" },
  { source: "server/services/gmailIntakeAdapters.ts:244", reason: "新表首航:同上,0117 尚未套用,EXPLAIN 不可行。v5(Codex 17 輪 §四.1)requeue SET 內的 lastSeenHistoryId 單調 GREATEST 片段(併入 238 的整條 UPDATE 一起彩排):同一 requeue UPDATE 原子推進已見水位(GREATEST(current, maxSeenEventId),BigInt CAST UNSIGNED,NULL-safe 雙向,不回退),使記消耗 + 重排 + 推水位無「先記消耗後重排」crash 縫隙。裸語句同 235 條(此 token 是該 UPDATE 的 SET 子片段):`lastSeenHistoryId` = case when `lastSeenHistoryId` is null then ? when ? is null then `lastSeenHistoryId` when cast(? as unsigned) > cast(`lastSeenHistoryId` as unsigned) then ? else `lastSeenHistoryId` end,sampleParams ['9007199254740999','9007199254740999','9007199254740999','9007199254740999'](cls B,CAST UNSIGNED 大數比較)。" },
  { source: "server/services/gmailIntakeAdapters.ts:267", reason: "新表首航:同上,0117 尚未套用,EXPLAIN 不可行。v6(Codex 18 輪 §四/§七 三值 MAX 消耗水位)requeue 的 WHERE 嚴格大於閘門片段(併入 238 的整條 UPDATE 一起彩排):只有本 label 事件 id 嚴格大於「本事件之前的已消耗水位」=(lastRequeueEventId, lastSeenHistoryId, scanConsumedFloor)三者非 NULL 值的數值 MAX 才重排(v5 的 COALESCE-first-non-null 是錯的——E10/E30 會取 E10 非 MAX=E30,讓 stale E20 誤重排)。MySQL NULL-safe max = GREATEST 三個 CAST UNSIGNED COALESCE 輪轉:任一非 NULL 值填滿每個輪轉故 GREATEST 為真 max;三者皆 NULL(scan 建列現已寫 scanConsumedFloor,理論全 NULL 才會發生)→ 每輪轉皆 NULL → GREATEST NULL → X>NULL→NULL→不重排(fail-closed,不是把 NULL 當 0 兜底;NULL 分支獨立處理)。replay 同一/較舊事件 affectedRows=0 不重複累加。裸語句同 238 條(此 token 是該 UPDATE 的 WHERE 子片段):cast(? as unsigned) > greatest(coalesce(cast(`lastRequeueEventId` as unsigned), cast(`lastSeenHistoryId` as unsigned), cast(`scanConsumedFloor` as unsigned)), coalesce(cast(`lastSeenHistoryId` as unsigned), cast(`scanConsumedFloor` as unsigned), cast(`lastRequeueEventId` as unsigned)), coalesce(cast(`scanConsumedFloor` as unsigned), cast(`lastRequeueEventId` as unsigned), cast(`lastSeenHistoryId` as unsigned))),sampleParams ['9007199254740999'](cls B,BigInt-precise CAST UNSIGNED 比較,避免字面大於 2^53 的字典序/Number 陷阱)。" },
  { source: "server/services/gmailIntakeAdapters.ts:308", reason: "新表首航:同上,0117 尚未套用,EXPLAIN 不可行;0117 套用後移入正式登記。v6(Codex 17 §四.2/.3 + Codex 18 §七 scan floor)發現寫入的 statement 2(現於 requeue 之後跑):最小發現列 insert,drizzle 對 .values() 每值綁參(含常量 internalDateMs=0 / status='pending' / discoveryReason='initial';多列一次 insert 時 VALUES 元組逐列重複),gmailHistoryId+lastSeenHistoryId 落 maxSeenEventId,lastRequeueEventId 落 labelEventId(§四.2 首次由 label 建列即記該事件已消耗;message_added/scan 為 null),scanConsumedFloor 落掃描前 baseline(scan/bootstrap 建列才有值;history 為 null),ON DUPLICATE KEY 只把 lastSeenHistoryId 改為 FORWARD-ONLY(CAST UNSIGNED 大數比較,NULL-safe 雙向,ODKU set 不碰 lastRequeueEventId/scanConsumedFloor/status):INSERT INTO `gmailIngestionLedger` (`integrationId`,`gmailMessageId`,`gmailThreadId`,`gmailHistoryId`,`lastSeenHistoryId`,`lastRequeueEventId`,`scanConsumedFloor`,`discoveryReason`,`internalDateMs`,`source`,`status`) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE `lastSeenHistoryId` = case when values(`lastSeenHistoryId`) is null then `lastSeenHistoryId` when `lastSeenHistoryId` is null then values(`lastSeenHistoryId`) when cast(values(`lastSeenHistoryId`) as unsigned) > cast(`lastSeenHistoryId` as unsigned) then values(`lastSeenHistoryId`) else `lastSeenHistoryId` end,sampleParams 每列(message_added history)[1,'m1','t1','H2','H2',null,null,'initial',0,'history','pending'];label 首建 [1,'m1','t1','H2','H2','H2',null,'initial',0,'history','pending'];scan 建列 [1,'ms','t-ms',null,null,null,'B_baseline','initial',0,'fallback_scan','pending'](cls B,sql`case ... end` 為 ODKU 片段)。" },
  { source: "server/services/gmailIntakeAdapters.ts:456", reason: "新表首航:同上,0117 尚未套用,EXPLAIN 不可行;0117 套用後移入正式登記。v4(Codex 16 輪 P0-3)claimActionable 的 CAS claim WHERE 片段(feeder 只搶已分類 customer/receipt pending 加重試到期 failed、且 lease 空閒的列):UPDATE `gmailIngestionLedger` SET `claimToken` = ?,`claimExpiresAt` = ?,`claimStage` = ? WHERE (`integrationId` = ? AND ((`status` = ? AND `route` IN (?, ?)) OR (`status` = ? AND `retryCount` <= ? AND `nextRetryAt` IS NOT NULL AND `nextRetryAt` <= ?)) AND (`claimToken` IS NULL OR `claimExpiresAt` <= ?)) ORDER BY `firstSeenAt` ASC LIMIT ?,sampleParams ['tok',NOW(),'feed',1,'pending','customer','receipt','failed',2,NOW(),NOW(),100](cls B,sql`nextRetryAt IS NOT NULL` 為片段)。註:advanceCursorCAS、claimUnclassified / renewClaim / releaseClaim / recordClassifyFailure / classify / markProcessed / markIgnored / markFailed 的 token-gated UPDATE、statement-1 requeue 其餘欄、statement-2 INSERT 其餘欄,均純 drizzle builder,除上列五個 raw token 外無其他 sql`` 出現點,不在盤點口徑內。" },
];
