/**
 * registryWhitelist.ts — C 類白名單:server/ 裡「不進 EXPLAIN 彩排」的 raw SQL 出現點。
 * 每條寫明理由。coverage.test.ts:每個 source 要嘛在此、要嘛在 ENTRIES.sources。
 */
import type { WhitelistEntry } from "./registry";

export const WHITELIST: WhitelistEntry[] = [
  { source: "server/_core/healthCheck.ts:161", reason: "SELECT 1 是純健康探測(liveness ping),不含任何表/欄位,不對應任何 schema 查詢,EXPLAIN 對它無意義(MySQL/TiDB 對 SELECT 1 的 EXPLAIN 只會顯示 'No tables used',沒有計畫可彩排)。" },
  { source: "server/_core/guestNoiseGate.ts:86", reason: "可重用 SQL 片段常量(qualifiesViaContent 之類 EXISTS(...) 片段),本身非獨立語句無法單獨 EXPLAIN;其 parse 由呼叫端 adminCustomers.buildGuestListQuery / runGuestUnreadRankingQuery 與 globalSearch.* 的已登記查詢覆蓋。" },
  { source: "server/_core/guestNoiseGate.ts:93", reason: "可重用 SQL 片段常量(latestInboundIsSpam 之類子查詢片段),本身非獨立語句;其 parse 由呼叫端 globalSearch.* / adminCustomers.* 的已登記查詢覆蓋。" },
  // ── gmail-intake-ledger 新表首航(0117 gmailIngestionLedger,prod 尚未套用)────
  // TODO(0117 上 prod 後):把下面三條移入 registryEntries 正式登記(裸語句見各條 reason),
  // 從白名單刪除。追蹤:docs/features/gmail-intake-ledger/progress.md。
  { source: "server/services/gmailIntakeAdapters.ts:202", reason: "新表首航:gmailIngestionLedger 由 migration 0117 建立,prod TiDB 尚未套用(migration 在 release_command 才跑,閘 6.5 的 EXPLAIN 在部署前執行),對不存在的表 EXPLAIN 必然 resolution 失敗,登記反而永紅 —— 無既有新表先例(0116 checkoutDisclosures / 0079 skillRuns 批皆無 raw SQL token)。0117 套用後移入正式登記。v3(Codex 15 輪 P0-2 狀態感知 upsert)發現寫入的 statement 1:最小發現列 insert,drizzle 對 .values() 每個值一律綁參(含常量 internalDateMs=0 / status='pending' / discoveryReason='initial',皆為 ?;多列一次 insert 時 VALUES 元組逐列重複),ON DUPLICATE KEY 只刷 lastSeenHistoryId 為新到 historyId:INSERT INTO `gmailIngestionLedger` (`integrationId`,`gmailMessageId`,`gmailThreadId`,`gmailHistoryId`,`lastSeenHistoryId`,`discoveryReason`,`internalDateMs`,`source`,`status`) VALUES (?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE `lastSeenHistoryId` = coalesce(values(`lastSeenHistoryId`), `lastSeenHistoryId`)(fallback 掃描的 NULL 不覆蓋既有值),sampleParams 每列 [1,'m1','t1','H2','H2','initial',0,'history','pending'](cls B,sql`coalesce(values(lastSeenHistoryId), lastSeenHistoryId)` 為 ODKU 片段)。" },
  { source: "server/services/gmailIntakeAdapters.ts:240", reason: "新表首航:同上,gmailIngestionLedger(0117)prod 尚未存在,EXPLAIN 不可行;0117 套用後移入正式登記。v3(Codex 15 輪 P0-2)狀態感知 upsert 的 statement 2:REQUEUE —— 只對本批中 eventKind=label_added_inbox 的 ids(§四.1 閘門,message_added/掃描發現絕不觸發;空集合直接略過本語句)把 status='ignored' 的列翻回 pending 重新分類並記稽核(requeueCount+1),`WHERE status='ignored'` 使 processed/failed/pending 為 no-op、replay 冪等,SET 無任何欄引用 status 故無 ODKU 賦值順序雷:UPDATE `gmailIngestionLedger` SET `status` = ?,`route` = ?,`wouldRoute` = ?,`classifiedAt` = ?,`fromAddress` = ?,`internalDateMs` = ?,`failureKind` = ?,`errorDetail` = ?,`httpStatus` = ?,`retryCount` = ?,`nextRetryAt` = ?,`processedAt` = ?,`interactionId` = ?,`discoveryReason` = ?,`lastRequeuedAt` = ?,`requeueCount` = `requeueCount` + 1 WHERE (`integrationId` = ? AND `gmailMessageId` IN (?) AND `status` = ?),sampleParams ['pending',null,null,null,null,0,null,null,null,0,null,null,null,'inbox_requeue',NOW(),1,'m1','ignored'](cls B,sql`requeueCount + 1` 為自增片段)。" },
  { source: "server/services/gmailIntakeAdapters.ts:348", reason: "新表首航:同上,gmailIngestionLedger(0117)prod 尚未存在,EXPLAIN 不可行;0117 套用後移入正式登記。listActionable 裸語句(feeder 只取已分類的 customer/receipt pending 加重試到期的 failed),drizzle 綁參形式(status/route/limit 全為 ?):SELECT * FROM `gmailIngestionLedger` WHERE (`integrationId` = ? AND ((`status` = ? AND `route` IN (?, ?)) OR (`status` = ? AND `retryCount` <= ? AND `nextRetryAt` IS NOT NULL AND `nextRetryAt` <= ?))) ORDER BY `firstSeenAt` ASC LIMIT ?,sampleParams [1,'pending','customer','receipt','failed',2,NOW(),100](cls B,sql`nextRetryAt IS NOT NULL` 為片段)。註:gmailIntegration 的 CAS UPDATE(advanceCursorCAS)、insertMinimalIgnore 的 statement-2 requeue UPDATE 的其餘欄、listUnclassified/recordClassifyFailure/classify 均純 drizzle builder,除上列三個 raw token 外無其他,不在盤點口徑內。" },
];
