import { Job } from "bullmq";
import {
  TourGenerationJobData,
  TourGenerationResult,
} from "./queue";
import { MasterAgent } from "./agents/masterAgent";
import { createTour } from "./db";
import { translateTour } from "./translation";
// Image supplementation removed for speed optimization
// import { supplementImages } from "./services/unsplashService";

/**
 * Internal tour generation function called by worker
 * Uses multi-agent system to generate tour from URL
 * 
 * @param url - Source URL to scrape
 * @param userId - User ID who requested the generation
 * @param job - BullMQ job for progress tracking
 */
export async function generateTourFromUrlInternal(
  url: string,
  userId: number,
  job: Job<TourGenerationJobData, TourGenerationResult>,
  forceRegenerate: boolean = false,
  isPdf: boolean = false
): Promise<TourGenerationResult> {
  console.log("[TourGenerator] Starting tour generation...");
  console.log("[TourGenerator] URL:", url);
  console.log("[TourGenerator] User ID:", userId);
  console.log("[TourGenerator] Force Regenerate:", forceRegenerate);
  console.log("[TourGenerator] Is PDF:", isPdf);
  
  try {
    // Create Master Agent
    const masterAgent = new MasterAgent();
    
    // Generate taskId for progress tracking
    const taskId = `gen_${Date.now()}_${Math.random().toString(36).substring(7)}`;
    
    // Import progressTracker for getting partial results
    const { progressTracker } = await import("./agents/progressTracker");
    
    // Execute tour generation with progress tracking
    const result = await masterAgent.execute(url, userId, async (step, percentage) => {
      // Get partial results from progressTracker
      const progressData = progressTracker.getProgress(taskId);
      const partialResults = progressData?.partialResults;
      
      // Update job progress with partial results
      await job.updateProgress({
        step,
        progress: percentage,
        message: `Processing: ${step}`,
        timestamp: Date.now(),
        partialResults: partialResults || undefined,
      });
    }, taskId, forceRegenerate, isPdf);
    
    if (!result.success || !result.data) {
      throw new Error(result.error || "Tour generation failed");
    }
    
    const tourData = result.data;
    
    // Image supplementation skipped - editors will manage images manually
    console.log('[TourGenerator] Skipping image supplement - editors will manage images');
    
    // Save to database
    await job.updateProgress({
      step: "saving",
      percentage: 95,
      message: "Saving tour to database...",
    });
    
    const tour = await createTour({
      title: tourData.title,
      description: tourData.description,
      productCode: tourData.productCode,
      destinationCountry: tourData.destinationCountry,
      destinationCity: tourData.destinationCity,
      departureCity: tourData.departureCity,
      duration: tourData.days,
      nights: tourData.nights,
      price: tourData.price,
      destination: tourData.destinationCity || tourData.destinationCountry, // Legacy field for compatibility
      tags: JSON.stringify(tourData.tags),
      
      // Hero section
      heroImage: tourData.heroImage,
      heroImageAlt: tourData.heroImageAlt,
      heroSubtitle: tourData.heroSubtitle,
      
      // Color theme and features
      colorTheme: tourData.colorTheme,
      keyFeatures: tourData.keyFeatures,
      poeticContent: tourData.poeticContent,
      featureImages: tourData.featureImages,
      highlights: tourData.highlights,
      
      // Detailed content from agents (CRITICAL: These fields were missing!)
      itineraryDetailed: tourData.itineraryDetailed, // 每日行程
      costExplanation: tourData.costExplanation, // 費用說明
      noticeDetailed: tourData.noticeDetailed, // 注意事項
      hotels: tourData.hotels, // 飯店介紹
      meals: tourData.meals, // 餐飲介紹
      flights: tourData.flights, // 航班資訊
      
      // Additional fields
      status: "active",
      featured: 0, // 0 = false, 1 = true
      promotionText: "",
      
      // Metadata
      createdBy: userId,
      sourceUrl: tourData.sourceUrl,
      originalityScore: tourData.originalityScore.toString(), // Convert to string for decimal field
      isAutoGenerated: 1, // Mark as auto-generated
    });
    
    console.log("[TourGenerator] Tour saved to database with ID:", tour.id);
    
    await job.updateProgress({
      step: "completed",
      percentage: 100,
      message: "Tour generation completed!",
    });
    
    // 非同步觸發翻譯（不阻塞生成流程）
    translateTour(tour.id, ['en'], 'zh-TW', userId)
      .then((result) => {
        if (result.success) {
          console.log(`[TourGenerator] Auto-translated tour ${tour.id} to: ${result.translatedLanguages.join(', ')}`);
        } else {
          console.warn(`[TourGenerator] Auto-translation failed for tour ${tour.id}:`, result.errors);
        }
      })
      .catch((err) => {
        console.warn(`[TourGenerator] Auto-translation error for tour ${tour.id}:`, err);
      });
    
    return {
      success: true,
      tourId: tour.id,
    };
  } catch (error) {
    console.error("[TourGenerator] Error:", error);
    return {
      success: false,
      error: error instanceof Error ? error.message : "Unknown error",
    };
  }
}
