import { useAuth } from "@/_core/hooks/useAuth";
import { useLocale } from "@/contexts/LocaleContext";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import DeparturesManagement from "./DeparturesManagement";
import DeparturePreview from "./DeparturePreview";
import { GenerationProgressComponent } from "./GenerationProgress";
import { TourEditDialog } from "./TourEditDialog";
import { Calendar, ChevronDown, Copy, Edit, Eye, EyeOff, ExternalLink, FileUp, Globe, Loader2, MoreHorizontal, Plus, RefreshCw, Search, Sparkles, Star, Trash2, Upload } from "lucide-react";
import { LoadingRow } from "@/components/ui/spinner";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { useState, useEffect } from "react";
import { toast } from "sonner";

type TourFormData = {
  title: string;
  destination: string;
  destinationCountry: string;
  destinationCity: string;
  description: string;
  duration: number;
  price: number;
  imageUrl?: string;
  category: "group" | "custom" | "package" | "cruise" | "theme";
  status: "active" | "inactive" | "soldout";
  featured: number;
  maxParticipants?: number;
  highlights?: string;
  includes?: string;
  excludes?: string;
};

export default function ToursTab() {
  const { user } = useAuth();
  const isAdmin = user?.role === "admin";
  const { t } = useLocale();
  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false);
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false);
  const [isBatchDeleteDialogOpen, setIsBatchDeleteDialogOpen] = useState(false);
  const [isAutoGenerateDialogOpen, setIsAutoGenerateDialogOpen] = useState(false);
  const [isPreviewDialogOpen, setIsPreviewDialogOpen] = useState(false);
  const [isEditDialogOpen2, setIsEditDialogOpen2] = useState(false);
  const [isFullEditDialogOpen, setIsFullEditDialogOpen] = useState(false);
  const [selectedTourForEdit, setSelectedTourForEdit] = useState<any>(null);
  const [isDeparturesDialogOpen, setIsDeparturesDialogOpen] = useState(false);
  const [selectedTourForDepartures, setSelectedTourForDepartures] = useState<{id: number, title: string} | null>(null);
  const [isAiDeparturePreviewOpen, setIsAiDeparturePreviewOpen] = useState(false);
  const [selectedTourForAiPreview, setSelectedTourForAiPreview] = useState<{id: number, title: string} | null>(null);
  const [autoGenerateUrl, setAutoGenerateUrl] = useState("");
  const [forceRegenerate, setForceRegenerate] = useState(false);
  const [pdfFile, setPdfFile] = useState<File | null>(null);
  const [pdfUploading, setPdfUploading] = useState(false);
  const [inputMode, setInputMode] = useState<"url" | "pdf" | "pdf_url">("pdf");  // PDF is the recommended and default mode
  const [supplementUrl, setSupplementUrl] = useState(""); // 供應商官網 URL（PDF+URL 模式）
  const [generatedTourData, setGeneratedTourData] = useState<any>(null);
  const [extractionStep, setExtractionStep] = useState<number>(0); // 0: 未開始, 1: 抓取網頁, 2: 解析內容, 3: AI 分析, 4: 預覽準備完成
  const [currentTaskId, setCurrentTaskId] = useState<string | null>(null); // 用於進度追蹤
  const [isGenerating, setIsGenerating] = useState(false); // 是否正在生成
  const [generationError, setGenerationError] = useState<string | null>(null); // 生成失敗錯誤訊息
  const [selectedTourId, setSelectedTourId] = useState<number | null>(null);
  const [selectedTourIds, setSelectedTourIds] = useState<number[]>([]);
  const [statusFilter, setStatusFilter] = useState<"all" | "active" | "inactive">("all");
  const [featuredFilter, setFeaturedFilter] = useState<"all" | "featured" | "normal">("all");
  const [searchKeyword, setSearchKeyword] = useState<string>("");
  const [sortBy, setSortBy] = useState<"default" | "price-asc" | "price-desc" | "duration-asc" | "duration-desc" | "date-asc" | "date-desc">("default");
  const [formData, setFormData] = useState<TourFormData>({
    title: "",
    destination: "",
    destinationCountry: "",
    destinationCity: "",
    description: "",
    duration: 1,
    price: 0,
    imageUrl: "",
    category: "group",
    status: "active",
    featured: 0,
    maxParticipants: undefined,
    highlights: "",
    includes: "",
    excludes: "",
  });

  const utils = trpc.useUtils();
  const { data: tours, isLoading: toursLoading } = trpc.tours.list.useQuery();
  
  const createTourMutation = trpc.tours.create.useMutation({
    onSuccess: () => {
      utils.tours.list.invalidate();
      setIsCreateDialogOpen(false);
      resetForm();
      toast.success(t('toursTab.createSuccess'));
    },
    onError: (error) => {
      toast.error(t('toursTab.createError').replace('{message}', error.message));
    },
  });

  const updateTourMutation = trpc.tours.update.useMutation({
    onSuccess: () => {
      utils.tours.list.invalidate();
      setIsEditDialogOpen(false);
      setIsFullEditDialogOpen(false);
      resetForm();
      toast.success(t('toursTab.updateSuccess'));
    },
    onError: (error) => {
      toast.error(t('toursTab.updateError').replace('{message}', error.message));
    },
  });

  const deleteTourMutation = trpc.tours.delete.useMutation({
    onSuccess: () => {
      utils.tours.list.invalidate();
      setIsDeleteDialogOpen(false);
      setSelectedTourId(null);
      toast.success(t('toursTab.deleteSuccess'));
    },
    onError: (error) => {
      toast.error(t('toursTab.deleteError').replace('{message}', error.message));
    },
  });

  const batchDeleteToursMutation = trpc.tours.batchDelete.useMutation({
    onSuccess: () => {
      utils.tours.list.invalidate();
      setIsBatchDeleteDialogOpen(false);
      setSelectedTourIds([]);
      toast.success(t('toursTab.batchDeleteSuccess'));
    },
    onError: (error) => {
      toast.error(t('toursTab.batchDeleteError').replace('{message}', error.message));
    },
  });

  const toggleStatusMutation = trpc.tours.toggleStatus.useMutation({
    onSuccess: () => {
      utils.tours.list.invalidate();
      toast.success(t('toursTab.statusUpdateSuccess'));
    },
    onError: (error) => {
      toast.error(t('toursTab.statusUpdateError').replace('{message}', error.message));
    },
  });

  const toggleFeaturedMutation = trpc.tours.toggleFeatured.useMutation({
    onSuccess: () => {
      utils.tours.list.invalidate();
      toast.success(t('toursTab.featuredUpdateSuccess'));
    },
    onError: (error) => {
      toast.error(t('toursTab.featuredUpdateError').replace('{message}', error.message));
    },
  });

  // 快速修改分類 mutation
  const patchFieldMutation = trpc.tours.patchField.useMutation({
    onSuccess: () => {
      utils.tours.list.invalidate();
      toast.success('分類已更新');
    },
    onError: (error) => {
      toast.error(`更新失敗：${error.message}`);
    },
  });

  // 分類標籤顯示
  const CATEGORY_LABELS: Record<string, { label: string; color: string }> = {
    group:   { label: '團體旅遊', color: 'bg-blue-100 text-blue-700' },
    custom:  { label: '客製旅遊', color: 'bg-purple-100 text-purple-700' },
    package: { label: '包團旅遊', color: 'bg-green-100 text-green-700' },
    cruise:  { label: '郵輪旅遊', color: 'bg-cyan-100 text-cyan-700' },
    theme:   { label: '主題旅遊', color: 'bg-orange-100 text-orange-700' },
  };

  // 複製行程 mutation
  const duplicateTourMutation = trpc.tours.duplicate.useMutation({
    onSuccess: (newTour) => {
      utils.tours.list.invalidate();
      toast.success(`${t('toursTab.copyTour')} - ${newTour.title}`);
    },
    onError: (error) => {
      toast.error(t('toursTab.createError').replace('{message}', error.message));
    },
  });

  // 複製行程處理函數
  const handleDuplicate = (tourId: number, tourTitle: string) => {
    if (confirm(`${t('toursTab.copyTour')} - ${tourTitle}?`)) {
      duplicateTourMutation.mutate({ id: tourId });
    }
  };

  // 異步生成 mutation
  const submitAsyncGenerationMutation = trpc.tours.submitAsyncGeneration.useMutation({
    onSuccess: (result) => {
      console.log("[SubmitAsyncGeneration] Job submitted:", result.jobId);
      setCurrentTaskId(result.jobId);
      setIsGenerating(true);
      setExtractionStep(1); // 開始生成
      toast.success(result.message || t('toursTab.generationSubmitted'));
    },
    onError: (error) => {
      setExtractionStep(0);
      setIsGenerating(false);
      setCurrentTaskId(null);
      console.error("[SubmitAsyncGeneration] Error:", error);
      setGenerationError(error.message); // 顯示持久錯誤 UI
    },
  });

  // 輪詢生成狀態
  const { data: generationStatus } = trpc.tours.getGenerationStatus.useQuery(
    { jobId: currentTaskId || "" },
    {
      enabled: !!currentTaskId && isGenerating,
      refetchInterval: 3000, // 每 3 秒輪詢一次（避免 Cloudflare 超時）
    }
  );

  // 監聽生成狀態變化
  useEffect(() => {
    if (!generationStatus) return;
    
    console.log("[GenerationStatus]", generationStatus);
    
    // 更新進度
    if (generationStatus.progressDetails) {
      const progress = generationStatus.progressDetails.progress || 0;
      
      // 根據進度更新步驟
      if (progress < 30) {
        setExtractionStep(1); // 抓取中
      } else if (progress < 90) {
        setExtractionStep(2); // 生成中
      } else if (progress < 100) {
        setExtractionStep(3); // 儲存中
      }
    }
    
    // 檢查是否完成
    if (generationStatus.status === "completed") {
      setExtractionStep(4); // 完成
      setIsGenerating(false);
      setCurrentTaskId(null);
      setIsAutoGenerateDialogOpen(false);
      setAutoGenerateUrl("");
      setExtractionStep(0);
      
      // 刷新行程列表
      utils.tours.list.invalidate();
      
      if (generationStatus.result?.success) {
        toast.success(
          t('toursTab.generationSuccess'),
          {
            description: generationStatus.result.tourId ? t('toursTab.tourIdLabel').replace('{id}', String(generationStatus.result.tourId)) : undefined,
            duration: 5000,
          }
        );
      }
    }
    
    // 檢查是否失敗
    if (generationStatus.status === "failed") {
      setExtractionStep(0);
      setIsGenerating(false);
      setCurrentTaskId(null);
      // 設置錯誤訊息，保持對話框開啟以顯示錯誤 UI
      setGenerationError(generationStatus.failedReason || t('toursTab.unknownError'));
    }
  }, [generationStatus]);

  // 從預覽儲存 mutation
  const saveFromPreviewMutation = trpc.tours.saveFromPreview.useMutation({
    onSuccess: (result) => {
      utils.tours.list.invalidate();
      setIsPreviewDialogOpen(false);
      setGeneratedTourData(null);
      setAutoGenerateUrl("");
      setExtractionStep(0);
      toast.success(
        result.message || t('toursTab.saveTourSuccess'),
        {
          description: t('toursTab.tourIdLabel').replace('{id}', String(result.tourId)),
          duration: 5000,
        }
      );
    },
    onError: (error) => {
      toast.error(t('toursTab.updateError').replace('{message}', error.message));
    },
  });

  const handleAutoGenerate = async () => {
    setGenerationError(null); // 重試時清除上次的錯誤狀態
    if (inputMode === "url") {
      // 模式 1：URL only
      if (!autoGenerateUrl.trim()) {
        toast.error(t('toursTab.enterUrl'));
        return;
      }
      // B6 fix: validate URL format
      try {
        const parsed = new URL(autoGenerateUrl.trim());
        if (!['http:', 'https:'].includes(parsed.protocol)) throw new Error();
      } catch {
        toast.error(t('toursTab.invalidUrl') || '請輸入有效的 URL（需以 http:// 或 https:// 開頭）');
        return;
      }
      submitAsyncGenerationMutation.mutate({ 
        url: autoGenerateUrl,
        forceRegenerate,
        isPdf: false,
      });
    } else if (inputMode === "pdf") {
      // 模式 2：PDF only
      if (!pdfFile) {
        toast.error(t('toursTab.selectPdf'));
        return;
      }
      
      try {
        setPdfUploading(true);
        toast.info(t('toursTab.uploadingPdf'));
        
        const formData = new FormData();
        formData.append("pdf", pdfFile);
        
        const uploadResponse = await fetch("/api/pdf/upload", {
          method: "POST",
          body: formData,
        });
        
        if (!uploadResponse.ok) {
          throw new Error(t('toursTab.pdfUploadFailed'));
        }
        
        const { url: pdfUrl } = await uploadResponse.json();
        console.log("[PDF Upload] Uploaded to:", pdfUrl);
        
        setPdfUploading(false);
        toast.success(t('toursTab.pdfUploadSuccess'));
        
        submitAsyncGenerationMutation.mutate({ 
          url: pdfUrl,
          forceRegenerate,
          isPdf: true,
        });
      } catch (error: any) {
        setPdfUploading(false);
        console.error("[PDF Upload] Error:", error);
        toast.error(t('toursTab.pdfUploadError').replace('{message}', error.message));
      }
    } else {
      // 模式 3：PDF + URL
      if (!pdfFile) {
        toast.error(t('toursTab.selectPdf'));
        return;
      }
      if (!supplementUrl.trim()) {
        toast.error('請輸入供應商官網 URL');
        return;
      }
      // B6 fix: validate supplementUrl format
      try {
        const parsed = new URL(supplementUrl.trim());
        if (!['http:', 'https:'].includes(parsed.protocol)) throw new Error();
      } catch {
        toast.error(t('toursTab.invalidUrl') || '請輸入有效的 URL（需以 http:// 或 https:// 開頭）');
        return;
      }
      
      try {
        setPdfUploading(true);
        toast.info(t('toursTab.uploadingPdf'));
        
        const formData = new FormData();
        formData.append("pdf", pdfFile);
        
        const uploadResponse = await fetch("/api/pdf/upload", {
          method: "POST",
          body: formData,
        });
        
        if (!uploadResponse.ok) {
          throw new Error(t('toursTab.pdfUploadFailed'));
        }
        
        const { url: pdfUrl } = await uploadResponse.json();
        console.log("[PDF+URL] PDF uploaded to:", pdfUrl);
        console.log("[PDF+URL] Supplement URL:", supplementUrl);
        
        setPdfUploading(false);
        toast.success('📎 PDF 上傳成功，正在結合官網資料生成...');
        
        submitAsyncGenerationMutation.mutate({ 
          url: pdfUrl,
          forceRegenerate,
          isPdf: true,
          supplementUrl: supplementUrl.trim(),
        });
      } catch (error: any) {
        setPdfUploading(false);
        console.error("[PDF+URL] Error:", error);
        toast.error(t('toursTab.pdfUploadError').replace('{message}', error.message));
      }
    }
  };

  const handleConfirmGeneratedTour = () => {
    if (generatedTourData) {
      // 使用 saveFromPreview mutation 儲存
      saveFromPreviewMutation.mutate({ tourData: generatedTourData });
    }
  };

  const handleRegenerate = () => {
    // 關閉預覽對話框，重新打開生成對話框
    setIsPreviewDialogOpen(false);
    setGeneratedTourData(null);
    setIsAutoGenerateDialogOpen(true);
    setExtractionStep(0);
  };

  const resetForm = () => {
    setFormData({
      title: "",
      destination: "",
      destinationCountry: "",
      destinationCity: "",
      description: "",
      duration: 1,
      price: 0,
      imageUrl: "",
      category: "group",
      status: "active",
      featured: 0,
      maxParticipants: undefined,
      highlights: "",
      includes: "",
      excludes: "",
    });
  };

  const handleCreate = () => {
    if (!formData.title || !formData.destination) {
      toast.error(t('toursTab.fillRequired'));
      return;
    }
    createTourMutation.mutate(formData);
  };

  const handleEdit = (tourId: number) => {
    const tour = tours?.find((t) => t.id === tourId);
    if (tour) {
      setSelectedTourId(tourId);
      // 轉換為 TourEditDialog 需要的格式
      const tourDataForEdit = {
        // Basic Info
        title: tour.title,
        destination: tour.destination,
        destinationCountry: tour.destinationCountry || "",
        destinationCity: tour.destinationCity || "",
        description: tour.description || "",
        duration: tour.duration,
        price: tour.price,
        priceCurrency: (tour as any).priceCurrency || "TWD",
        // Images
        heroImage: tour.heroImage || "",
        heroSubtitle: (tour as any).heroSubtitle || "",
        imageUrl: tour.imageUrl || "",
        // Category & Status
        category: tour.category,
        status: tour.status,
        featured: tour.featured || 0,
        maxParticipants: tour.maxParticipants || undefined,
        // Content
        highlights: tour.highlights || "",
        includes: tour.includes || "",
        excludes: tour.excludes || "",
        keyFeatures: (tour as any).keyFeatures || "",
        attractions: (tour as any).attractions || "",
        // Itinerary & Details
        itinerary: (tour as any).itinerary || [],
        itineraryDetailed: (tour as any).itineraryDetailed || "",
        hotels: tour.hotels || [],
        meals: (tour as any).meals || "",
        flights: tour.flights || null,
        images: (tour as any).images || [],
        galleryImages: (tour as any).galleryImages || "",
        costExplanation: tour.costExplanation || null,
        noticeDetailed: (tour as any).noticeDetailed || "",
        poeticContent: (tour as any).poeticContent || "",
        colorTheme: tour.colorTheme || null,
        // Extra fields
        productCode: (tour as any).productCode || "",
        promotionText: (tour as any).promotionText || "",
        departureCity: (tour as any).departureCity || "",
        departureAirportName: (tour as any).departureAirportName || "",
        notes: tour.notes || null,
        sourceUrl: tour.sourceUrl || "",
      };
      setSelectedTourForEdit(tourDataForEdit);
      setIsFullEditDialogOpen(true);
    }
  };

  const handleUpdate = () => {
    if (selectedTourId) {
      updateTourMutation.mutate({
        id: selectedTourId,
        ...formData,
      });
    }
  };

  const handleDelete = (tourId: number) => {
    setSelectedTourId(tourId);
    setIsDeleteDialogOpen(true);
  };

  const confirmDelete = () => {
    if (selectedTourId) {
      deleteTourMutation.mutate({ id: selectedTourId });
    }
  };

  const handleBatchDelete = () => {
    if (selectedTourIds.length === 0) {
      toast.error(t('toursTab.selectToDelete'));
      return;
    }
    setIsBatchDeleteDialogOpen(true);
  };

  const confirmBatchDelete = () => {
    batchDeleteToursMutation.mutate({ ids: selectedTourIds });
  };

  const toggleSelectTour = (tourId: number) => {
    setSelectedTourIds((prev) =>
      prev.includes(tourId)
        ? prev.filter((id) => id !== tourId)
        : [...prev, tourId]
    );
  };

  const toggleSelectAll = () => {
    if (filteredTours && selectedTourIds.length === filteredTours.length) {
      setSelectedTourIds([]);
    } else if (filteredTours) {
      setSelectedTourIds(filteredTours.map((t) => t.id));
    }
  };

  // Filter and sort tours
  const filteredTours = tours
    ?.filter((tour) => {
      if (statusFilter !== "all" && tour.status !== statusFilter) return false;
      if (featuredFilter === "featured" && tour.featured !== 1) return false;
      if (featuredFilter === "normal" && tour.featured === 1) return false;
      if (searchKeyword) {
        const keyword = searchKeyword.toLowerCase();
        return (
          tour.title.toLowerCase().includes(keyword) ||
          tour.destination.toLowerCase().includes(keyword) ||
          (tour.destinationCountry?.toLowerCase().includes(keyword)) ||
          (tour.destinationCity?.toLowerCase().includes(keyword))
        );
      }
      return true;
    })
    .sort((a, b) => {
      switch (sortBy) {
        case "price-asc":
          return a.price - b.price;
        case "price-desc":
          return b.price - a.price;
        case "duration-asc":
          return a.duration - b.duration;
        case "duration-desc":
          return b.duration - a.duration;
        case "date-asc":
          return new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime();
        case "date-desc":
          return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
        default:
          return 0;
      }
    });

  const getExtractionStepText = (step: number) => {
    switch (step) {
      case 1:
        return t('toursTab.stepFetching');
      case 2:
        return t('toursTab.stepParsing');
      case 3:
        return t('toursTab.stepAnalyzing');
      case 4:
        return t('toursTab.stepReady');
      default:
        return "";
    }
  };

  return (
    <div className="space-y-6">
      {/* Floating background generation indicator */}
      {isGenerating && !isAutoGenerateDialogOpen && (
        <div
          className="fixed bottom-6 right-6 z-50 bg-gray-900 text-white rounded-xl shadow-2xl px-4 py-3 flex items-center gap-3 cursor-pointer"
          onClick={() => setIsAutoGenerateDialogOpen(true)}
        >
          <Loader2 className="h-4 w-4 animate-spin text-purple-400" />
          <div>
            <p className="text-xs font-semibold">AI 行程生成中...</p>
            <p className="text-[10px] text-gray-400">點擊查看進度</p>
          </div>
        </div>
      )}

      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold tracking-tight">{t('toursTab.title')}</h2>
          <p className="text-gray-500 text-sm mt-1">
            {t('toursTab.subtitle')}
            {filteredTours && (
              <span className="ml-2 text-gray-400">（共 {filteredTours.length} 筆）</span>
            )}
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          {selectedTourIds.length > 0 && (
            <Button
              variant="outline"
              onClick={handleBatchDelete}
              className="border-red-200 text-red-600 hover:bg-red-50 hover:border-red-300"
            >
              <Trash2 className="h-4 w-4 mr-2" />
              刪除已選 ({selectedTourIds.length})
            </Button>
          )}
          <Button
            variant="outline"
            onClick={() => setIsAutoGenerateDialogOpen(true)}
            className="border-gray-300 text-gray-700 hover:bg-gray-50"
          >
            <Sparkles className="h-4 w-4 mr-2" />
            AI 生成行程
          </Button>
          <Button
            onClick={() => setIsCreateDialogOpen(true)}
            className="bg-black text-white hover:bg-gray-800"
          >
            <Plus className="h-4 w-4 mr-2" />
            新增行程
          </Button>
        </div>
      </div>

      {/* Filters */}
      <div className="flex flex-wrap gap-3 items-center p-4 bg-white border border-gray-200">
        <div className="flex-1 min-w-[220px]">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
            <Input
              placeholder="搜尋行程名稱、目的地..."
              value={searchKeyword}
              onChange={(e) => setSearchKeyword(e.target.value)}
              className="pl-10 border-gray-300"
            />
          </div>
        </div>
        <Select value={statusFilter} onValueChange={(v: any) => setStatusFilter(v)}>
          <SelectTrigger className="w-[130px] border-gray-300">
            <SelectValue placeholder="狀態" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">全部狀態</SelectItem>
            <SelectItem value="active">上架中</SelectItem>
            <SelectItem value="inactive">已下架</SelectItem>
          </SelectContent>
        </Select>
        <Select value={featuredFilter} onValueChange={(v: any) => setFeaturedFilter(v)}>
          <SelectTrigger className="w-[130px] border-gray-300">
            <SelectValue placeholder="精選" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">全部行程</SelectItem>
            <SelectItem value="featured">★ 精選行程</SelectItem>
            <SelectItem value="normal">一般行程</SelectItem>
          </SelectContent>
        </Select>
        <Select value={sortBy} onValueChange={(v: any) => setSortBy(v)}>
          <SelectTrigger className="w-[150px] border-gray-300">
            <SelectValue placeholder="排序" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="default">預設排序</SelectItem>
            <SelectItem value="price-asc">價格 由低到高</SelectItem>
            <SelectItem value="price-desc">價格 由高到低</SelectItem>
            <SelectItem value="duration-asc">天數 由短到長</SelectItem>
            <SelectItem value="duration-desc">天數 由長到短</SelectItem>
            <SelectItem value="date-desc">最新新增</SelectItem>
            <SelectItem value="date-asc">最早新增</SelectItem>
          </SelectContent>
        </Select>
        {(searchKeyword || statusFilter !== "all" || featuredFilter !== "all") && (
          <button
            onClick={() => { setSearchKeyword(""); setStatusFilter("all"); setFeaturedFilter("all"); }}
            className="text-sm text-gray-500 hover:text-gray-700 underline"
          >
            清除篩選
          </button>
        )}
      </div>

      {/* Tours Table */}
      <div className="bg-white border border-gray-200 overflow-hidden rounded-xl">
        {toursLoading ? (
          <LoadingRow text={t('toursTab.loading')} />
        ) : filteredTours && filteredTours.length > 0 ? (
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-50 border-b border-gray-200">
                <tr>
                  <th className="px-5 py-4 text-left w-10">
                    <Checkbox
                      checked={filteredTours.length > 0 && selectedTourIds.length === filteredTours.length}
                      onCheckedChange={toggleSelectAll}
                    />
                  </th>
                  <th className="px-5 py-4 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">行程名稱</th>
                  <th className="px-5 py-4 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider min-w-[140px]">目的地</th>
                  <th className="px-5 py-4 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">分類</th>
                  <th className="px-5 py-4 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">天數</th>
                  <th className="px-5 py-4 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">售價</th>
                  <th className="px-5 py-4 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">狀態</th>
                  <th className="px-5 py-4 text-right text-xs font-semibold text-gray-500 uppercase tracking-wider">操作</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {filteredTours.map((tour) => (
                  <tr key={tour.id} className="hover:bg-gray-50 transition-colors border-b border-gray-100 last:border-0">
                    <td className="px-5 py-5">
                      <Checkbox
                        checked={selectedTourIds.includes(tour.id)}
                        onCheckedChange={() => toggleSelectTour(tour.id)}
                      />
                    </td>
                    <td className="px-5 py-5">
                      <div className="flex items-center gap-4">
                        {tour.imageUrl ? (
                          <img
                            src={tour.imageUrl}
                            alt={tour.title}
                            className="h-14 w-20 object-cover rounded flex-shrink-0"
                          />
                        ) : (
                          <div className="h-14 w-20 bg-gray-100 rounded flex items-center justify-center flex-shrink-0">
                            <span className="text-gray-400 text-xs">無圖片</span>
                          </div>
                        )}
                        <div className="min-w-0">
                          <p className="font-semibold text-gray-900 line-clamp-1 text-sm">{tour.title}</p>
                          {tour.isAutoGenerated === 1 && (
                            <div className="flex items-center gap-2 flex-wrap">
                              <span className="inline-flex items-center gap-1 text-xs text-purple-600">
                                <Sparkles className="h-3 w-3" />
                {t('toursTab.aiGenerated')}
              </span>
                              {/* A3: Calibration QA badge — backend verdicts are 'approved' | 'review' | 'rejected' */}
                              {(tour as any).calibrationVerdict && (() => {
                                const verdict = (tour as any).calibrationVerdict;
                                const isApproved = verdict === 'approved' || verdict === 'pass';
                                const isReview = verdict === 'review' || verdict === 'warn';
                                const badgeClass = isApproved
                                  ? 'bg-green-100 text-green-700'
                                  : isReview
                                  ? 'bg-yellow-100 text-yellow-700'
                                  : 'bg-red-100 text-red-700';
                                const icon = isApproved ? '✅' : isReview ? '⚠️' : '❌';
                                return (
                                  <span className={`inline-flex items-center gap-1 text-xs px-1.5 py-0.5 rounded-full font-medium ${badgeClass}`} title={`AI 品質評分: ${(tour as any).calibrationScore ?? '-'}/100`}>
                                    {icon}
                                    {(tour as any).calibrationScore != null ? `${(tour as any).calibrationScore}分` : 'QA'}
                                  </span>
                                );
                              })()}
                              {tour.sourceUrl && (
                                <a
                                  href={tour.sourceUrl}
                                  target="_blank"
                                  rel="noopener noreferrer"
                                  className="inline-flex items-center gap-1 text-xs text-blue-500 hover:text-blue-700 hover:underline"
                                  title={t('toursTab.viewSource')}
                                  onClick={(e) => e.stopPropagation()}
                                >
                                  <ExternalLink className="h-3 w-3" />
                  {t('toursTab.originalLink')}
                </a>
                              )}
                            </div>
                          )}
                        </div>
                      </div>
                    </td>
                    <td className="px-5 py-5 text-sm min-w-[140px]">
                      <div className="font-medium text-gray-800 whitespace-nowrap">
                        {tour.destinationCountry || tour.destination}
                      </div>
                      {tour.destinationCity && (
                        <div className="text-xs text-gray-400 mt-0.5 whitespace-nowrap">{tour.destinationCity}</div>
                      )}
                    </td>
                    <td className="px-5 py-5">
                      <Select
                        value={tour.category}
                        onValueChange={(val) => patchFieldMutation.mutate({ id: tour.id, field: 'category', value: val })}
                      >
                        <SelectTrigger className={`h-7 text-xs border-0 px-2 py-0 w-[90px] font-medium rounded-full ${CATEGORY_LABELS[tour.category]?.color || 'bg-gray-100 text-gray-600'}`}>
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="group">團體旅遊</SelectItem>
                          <SelectItem value="custom">客製旅遊</SelectItem>
                          <SelectItem value="package">包團旅遊</SelectItem>
                          <SelectItem value="cruise">郵輪旅遊</SelectItem>
                          <SelectItem value="theme">主題旅遊</SelectItem>
                        </SelectContent>
                      </Select>
                    </td>
                    <td className="px-5 py-5 text-sm font-medium text-gray-700">{tour.duration} 天</td>
                    <td className="px-5 py-5 text-sm font-semibold text-gray-900">
                      NT$ {tour.price.toLocaleString()}
                    </td>
                    <td className="px-5 py-5">
                      <div className="flex flex-col gap-1">
                        <span
                          className={`inline-flex items-center px-2.5 py-0.5 text-xs font-semibold w-fit whitespace-nowrap ${
                            tour.status === "active"
                              ? "bg-black text-white"
                              : "bg-gray-100 text-gray-500 border border-gray-200"
                          }`}
                        >
                          {tour.status === "active" ? "● 上架中" : "○ 已下架"}
                        </span>
                        {tour.featured === 1 && (
                          <span className="inline-flex items-center px-2 py-0.5 text-xs font-medium bg-gray-700 text-white w-fit">
                            ★ 精選
                          </span>
                        )}
                      </div>
                    </td>
                    <td className="px-5 py-5">
                      <div className="flex items-center justify-end gap-1">
                        {/* 編輯按鈕 */}
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => handleEdit(tour.id)}
                          className="h-8 px-2 hover:bg-blue-50 transition-colors flex items-center gap-1 text-xs text-blue-600 rounded-lg"
                          title="編輯行程"
                        >
                          <Edit className="h-3.5 w-3.5" />
                          <span>編輯</span>
                        </Button>
                        {/* 更多操作下拉選單（上下架/精選/日期/複製/刪除） */}
                        <DropdownMenu>
                          <DropdownMenuTrigger asChild>
                            <Button
                              variant="ghost"
                              size="sm"
                              className="h-8 px-2 hover:bg-gray-100 transition-colors flex items-center gap-1 text-xs text-gray-600 rounded-lg"
                              title="更多操作"
                            >
                              <MoreHorizontal className="h-3.5 w-3.5 text-gray-500" />
                              <span>更多</span>
                            </Button>
                          </DropdownMenuTrigger>
                          <DropdownMenuContent align="end" className="w-44">
                            {/* 上下架 */}
                            <DropdownMenuItem
                              onClick={() => toggleStatusMutation.mutate({ id: tour.id })}
                              disabled={toggleStatusMutation.isPending}
                              className="cursor-pointer"
                            >
                              {tour.status === "active" ? (
                                <><EyeOff className="h-4 w-4 mr-2 text-gray-500" />下架行程</>
                              ) : (
                                <><Eye className="h-4 w-4 mr-2 text-green-600" />上架行程</>
                              )}
                            </DropdownMenuItem>
                            {/* 精選 */}
                            <DropdownMenuItem
                              onClick={() => toggleFeaturedMutation.mutate({ id: tour.id })}
                              disabled={toggleFeaturedMutation.isPending}
                              className="cursor-pointer"
                            >
                              <Star className={`h-4 w-4 mr-2 ${tour.featured === 1 ? "text-amber-500 fill-current" : "text-gray-400"}`} />
                              {tour.featured === 1 ? "取消精選" : "設為精選"}
                            </DropdownMenuItem>
                            {/* 出發日期 */}
                            <DropdownMenuItem
                              onClick={() => {
                                setSelectedTourForDepartures({id: tour.id, title: tour.title});
                                setIsDeparturesDialogOpen(true);
                              }}
                              className="cursor-pointer"
                            >
                              <Calendar className="h-4 w-4 mr-2 text-gray-500" />
                              管理出發日期
                            </DropdownMenuItem>
                            {/* AI 出發日預覽（只在有 extractedDepartures 時顯示） */}
                            {(tour as any).extractedDepartures && (
                              <DropdownMenuItem
                                onClick={() => {
                                  setSelectedTourForAiPreview({id: tour.id, title: tour.title});
                                  setIsAiDeparturePreviewOpen(true);
                                }}
                                className="cursor-pointer text-teal-700 focus:text-teal-700 focus:bg-teal-50"
                              >
                                <Sparkles className="h-4 w-4 mr-2 text-teal-600" />
                                AI 出發日預覽
                              </DropdownMenuItem>
                            )}
                            <DropdownMenuSeparator />
                            {/* 複製 */}
                            <DropdownMenuItem
                              onClick={() => handleDuplicate(tour.id, tour.title)}
                              disabled={duplicateTourMutation.isPending}
                              className="cursor-pointer"
                            >
                              <Copy className="h-4 w-4 mr-2 text-gray-500" />
                              複製行程
                            </DropdownMenuItem>
                            <DropdownMenuSeparator />
                            {/* 刪除 */}
                            <DropdownMenuItem
                              onClick={() => handleDelete(tour.id)}
                              className="cursor-pointer text-red-600 focus:text-red-600 focus:bg-red-50"
                            >
                              <Trash2 className="h-4 w-4 mr-2" />
                              刪除行程
                            </DropdownMenuItem>
                          </DropdownMenuContent>
                        </DropdownMenu>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : tours && tours.length > 0 ? (
          <div className="p-8 text-center">
            <p className="text-gray-600">{t('toursTab.noResults')}</p>
            <Button
              variant="link"
              onClick={() => {
                setStatusFilter("all");
                setFeaturedFilter("all");
              }}
              className="text-primary mt-2"
            >
              {t('common.clearFilters')}
            </Button>
          </div>
        ) : (
          <div className="p-8 text-center">
            <p className="text-gray-600">{t('toursTab.noData')}</p>
          </div>
        )}
      </div>

      {/* Create Dialog */}
      <Dialog open={isCreateDialogOpen} onOpenChange={setIsCreateDialogOpen}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto ">
          <DialogHeader>
            <DialogTitle>{t('toursTab.createDialogTitle')}</DialogTitle>
            <DialogDescription>{t('toursTab.createDialogDesc')}</DialogDescription>
          </DialogHeader>
          <TourForm formData={formData} setFormData={setFormData} />
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsCreateDialogOpen(false)}
              className=""
            >
              {t('common.cancel')}
            </Button>
            <Button
              onClick={handleCreate}
              disabled={createTourMutation.isPending}
              className="bg-black text-white hover:bg-gray-800"
            >
              {createTourMutation.isPending ? t('toursTab.creating') : t('toursTab.create')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Edit Dialog */}
      <Dialog open={isEditDialogOpen} onOpenChange={setIsEditDialogOpen}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto ">
          <DialogHeader>
            <DialogTitle>{t('toursTab.editDialogTitle')}</DialogTitle>
            <DialogDescription>{t('toursTab.editDialogDesc')}</DialogDescription>
          </DialogHeader>
          <TourForm formData={formData} setFormData={setFormData} />
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsEditDialogOpen(false)}
              className=""
            >
              {t('common.cancel')}
            </Button>
            <Button
              onClick={handleUpdate}
              disabled={updateTourMutation.isPending}
              className="bg-black text-white hover:bg-gray-800"
            >
              {updateTourMutation.isPending ? t('toursTab.updating') : t('toursTab.update')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete Dialog */}
      <Dialog open={isDeleteDialogOpen} onOpenChange={setIsDeleteDialogOpen}>
        <DialogContent className="">
          <DialogHeader>
            <DialogTitle>{t('toursTab.deleteDialogTitle')}</DialogTitle>
            <DialogDescription>
              {t('toursTab.deleteConfirmDesc')}
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsDeleteDialogOpen(false)}
              className=""
            >
              {t('common.cancel')}
            </Button>
            <Button
              variant="destructive"
              onClick={confirmDelete}
              disabled={deleteTourMutation.isPending}
              className=""
            >
              {deleteTourMutation.isPending ? t('toursTab.deleting') : t('toursTab.confirmDelete')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Batch Delete Dialog */}
      <Dialog open={isBatchDeleteDialogOpen} onOpenChange={setIsBatchDeleteDialogOpen}>
        <DialogContent className="">
          <DialogHeader>
            <DialogTitle>{t('toursTab.batchDeleteDialogTitle')}</DialogTitle>
            <DialogDescription>
              {t('toursTab.batchDeleteConfirmDesc').replace('{count}', String(selectedTourIds.length))}
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsBatchDeleteDialogOpen(false)}
              className=""
            >
              {t('common.cancel')}
            </Button>
            <Button
              variant="destructive"
              onClick={confirmBatchDelete}
              disabled={batchDeleteToursMutation.isPending}
              className=""
            >
              {batchDeleteToursMutation.isPending ? t('toursTab.deleting') : t('toursTab.confirmDelete')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Auto Generate Dialog */}
      <Dialog open={isAutoGenerateDialogOpen} onOpenChange={(open) => {
        if (!open) {
          setIsAutoGenerateDialogOpen(false);
          // If generating, keep taskId/isGenerating so polling continues in background
          if (!isGenerating) {
            setAutoGenerateUrl("");
            setForceRegenerate(false);
            setExtractionStep(0);
            setCurrentTaskId(null);
            setGenerationError(null); // 關閉對話框時清除錯誤狀態
          }
        }
      }}>
        <DialogContent className="max-w-lg ">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-purple-600" />
              {t('toursTab.aiAutoGenerateTitle')}
            </DialogTitle>
            <DialogDescription>
              {t('toursTab.aiAutoGenerateDesc')}
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            {/* 輸入模式選擇：三個模式切換 */}
            <div className="flex gap-1 p-1 bg-gray-100 rounded-lg">
              <button
                type="button"
                onClick={() => setInputMode("pdf")}
                disabled={isGenerating || pdfUploading}
                className={`flex-1 flex items-center justify-center gap-1.5 py-2 px-2 rounded-md text-xs font-medium transition-all ${
                  inputMode === "pdf"
                    ? "bg-white text-purple-700 shadow-sm"
                    : "text-gray-600 hover:text-gray-800"
                }`}
              >
                <FileUp className="h-3.5 w-3.5" />
                PDF 檔案
              </button>
              <button
                type="button"
                onClick={() => setInputMode("url")}
                disabled={isGenerating || pdfUploading}
                className={`flex-1 flex items-center justify-center gap-1.5 py-2 px-2 rounded-md text-xs font-medium transition-all ${
                  inputMode === "url"
                    ? "bg-white text-blue-700 shadow-sm"
                    : "text-gray-600 hover:text-gray-800"
                }`}
              >
                <Globe className="h-3.5 w-3.5" />
                官網 URL
              </button>
              <button
                type="button"
                onClick={() => setInputMode("pdf_url")}
                disabled={isGenerating || pdfUploading}
                className={`flex-1 flex items-center justify-center gap-1.5 py-2 px-2 rounded-md text-xs font-medium transition-all ${
                  inputMode === "pdf_url"
                    ? "bg-white text-green-700 shadow-sm"
                    : "text-gray-600 hover:text-gray-800"
                }`}
              >
                <Sparkles className="h-3.5 w-3.5" />
                PDF + URL
              </button>
            </div>

            {/* 模式說明 */}
            <div className={`text-xs rounded-lg px-3 py-2 ${
              inputMode === "pdf" ? "bg-purple-50 text-purple-700" :
              inputMode === "url" ? "bg-blue-50 text-blue-700" :
              "bg-green-50 text-green-700"
            }`}>
              {inputMode === "pdf" && "📌 上傳供應商提供的 PDF 行程表，AI 將自動解析內容"}
              {inputMode === "url" && "🌐 輸入供應商官網的行程頁面 URL，AI 動態爬取 + Vision 抽取日期/價格"}
              {inputMode === "pdf_url" && "✨ 同時上傳 PDF 並提供官網 URL，得到最完整的行程資料"}
            </div>

            {/* URL 輸入（URL 模式） */}
            {inputMode === "url" && (
              <div className="space-y-2">
                <Label className="text-sm font-medium">官網行程頁面 URL</Label>
                <input
                  type="url"
                  value={autoGenerateUrl}
                  onChange={(e) => setAutoGenerateUrl(e.target.value)}
                  placeholder="https://travel.liontravel.com/detail?..."
                  disabled={isGenerating}
                  className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>
            )}

            {/* PDF 上傳（PDF 模式 + PDF+URL 模式） */}
            {(inputMode === "pdf" || inputMode === "pdf_url") && (
              <div className="space-y-2">
                <Label>{t('toursTab.selectPdfFile')}</Label>
                <div 
                  className={`border-2 border-dashed rounded-lg p-6 text-center transition-colors ${
                    pdfFile 
                      ? "border-purple-300 bg-purple-50" 
                      : "border-gray-300 hover:border-purple-300 hover:bg-purple-50/50"
                  }`}
                >
                  <input
                    type="file"
                    accept=".pdf,application/pdf"
                    onChange={(e) => {
                      const file = e.target.files?.[0];
                      if (file) {
                        setPdfFile(file);
                      }
                    }}
                    disabled={isGenerating || pdfUploading}
                    className="hidden"
                    id="pdf-upload"
                  />
                  <label 
                    htmlFor="pdf-upload" 
                    className="cursor-pointer flex flex-col items-center gap-2"
                  >
                    {pdfFile ? (
                      <>
                        <FileUp className="h-8 w-8 text-purple-600" />
                        <span className="text-sm font-medium text-purple-600">{pdfFile.name}</span>
                        <span className="text-xs text-gray-500">
                          {(pdfFile.size / 1024 / 1024).toFixed(2)} MB
                        </span>
                      </>
                    ) : (
                      <>
                        <Upload className="h-8 w-8 text-gray-400" />
                        <span className="text-sm text-gray-600">{t('toursTab.dropPdfHint')}</span>
                        <span className="text-xs text-gray-400">{t('toursTab.pdfSupportHint')}</span>
                      </>
                    )}
                  </label>
                </div>
                {pdfFile && (
                  <button
                    type="button"
                    onClick={() => setPdfFile(null)}
                    className="text-xs text-red-500 hover:text-red-700"
                  >
                    {t('toursTab.clearFile')}
                  </button>
                )}
              </div>
            )}

            {/* 官網 URL 輸入（PDF+URL 模式） */}
            {inputMode === "pdf_url" && (
              <div className="space-y-2">
                <Label className="text-sm font-medium">
                  官網行程頁面 URL
                  <span className="ml-1.5 text-xs font-normal text-green-600">(用於 AI Vision 抽取日期/人數/價格)</span>
                </Label>
                <input
                  type="url"
                  value={supplementUrl}
                  onChange={(e) => setSupplementUrl(e.target.value)}
                  placeholder="https://travel.liontravel.com/detail?..."
                  disabled={isGenerating || pdfUploading}
                  className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent"
                />
              </div>
            )}
            
            {/* 強制重新生成選項 */}
            <div className="flex items-center space-x-2">
              <input
                type="checkbox"
                id="forceRegenerate"
                checked={forceRegenerate}
                onChange={(e) => setForceRegenerate(e.target.checked)}
                disabled={submitAsyncGenerationMutation.isPending || isGenerating}
                className="h-4 w-4 rounded border-gray-300 text-purple-600 focus:ring-purple-500"
              />
              <Label htmlFor="forceRegenerate" className="text-sm font-normal cursor-pointer">
                {t('toursTab.forceRegenerate')}
              </Label>
            </div>
            
            {/* Progress indicator - 使用新的進度條組件 */}
            {isGenerating && (
              <GenerationProgressComponent
                taskId={currentTaskId}
                isGenerating={isGenerating}
                pollingStatus={generationStatus}
                onComplete={() => {
                  console.log('[ToursTab] Generation complete callback');
                }}
                onError={(error) => {
                  console.error('[ToursTab] Generation error:', error);
                }}
              />
            )}

            {/* 生成失敗錯誤 UI */}
            {generationError && !isGenerating && (
              <div className="mt-3 p-4 bg-red-50 border border-red-200 rounded-lg">
                <div className="flex items-start gap-3">
                  <div className="flex-shrink-0 w-8 h-8 bg-red-100 rounded-full flex items-center justify-center">
                    <svg className="w-4 h-4 text-red-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                    </svg>
                  </div>
                  <div className="flex-1 min-w-0">
                    <h4 className="text-sm font-semibold text-red-800">{t('toursTab.generationFailed')}</h4>
                    <p className="text-xs text-red-600 mt-1">{t('toursTab.generationFailedDesc')}</p>
                    <details className="mt-2">
                      <summary className="text-xs text-red-500 cursor-pointer hover:text-red-700">{t('toursTab.errorDetails')}</summary>
                      <p className="text-xs text-red-500 mt-1 font-mono break-all">{generationError}</p>
                    </details>
                  </div>
                </div>
              </div>
            )}
          </div>
          <DialogFooter>
            {generationError && !isGenerating ? (
              // 失敗狀態：顯示返回輸入和重試按鈕
              <>
                <Button
                  variant="outline"
                  onClick={() => {
                    setGenerationError(null);
                  }}
                >
                  {t('toursTab.backToInput')}
                </Button>
                <Button
                  onClick={() => {
                    setGenerationError(null);
                    handleAutoGenerate();
                  }}
                  className="bg-purple-600 text-white hover:bg-purple-700 rounded-full"
                >
                  <RefreshCw className="h-4 w-4 mr-2" />
                  {t('toursTab.retryGeneration')}
                </Button>
              </>
            ) : (
              // 正常狀態：取消 / 縮小 + 開始生成
              <>
                <Button
                  variant="outline"
                  onClick={() => {
                    setIsAutoGenerateDialogOpen(false);
                    if (!isGenerating) {
                      // Only reset state if not generating
                      setAutoGenerateUrl("");
                      setForceRegenerate(false);
                      setExtractionStep(0);
                      setCurrentTaskId(null);
                      setPdfFile(null);
                      setPdfUploading(false);
                    }
                  }}
                  className=""
                >
                  {isGenerating ? t('toursTab.minimizeToBackground') || '縮小到背景' : t('common.cancel')}
                </Button>
                <Button
                  onClick={handleAutoGenerate}
                  disabled={submitAsyncGenerationMutation.isPending || isGenerating || pdfUploading || (
                    inputMode === "url" ? !autoGenerateUrl.trim() :
                    inputMode === "pdf" ? !pdfFile :
                    /* pdf_url */ (!pdfFile || !supplementUrl.trim())
                  )}
                  className="bg-purple-600 text-white hover:bg-purple-700 rounded-full"
                >
                  {(submitAsyncGenerationMutation.isPending || isGenerating || pdfUploading) ? (
                    <>
                      <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                      {t('toursTab.generating')}
                    </>
                  ) : (
                    <>
                      <Sparkles className="h-4 w-4 mr-2" />
                      {t('toursTab.startGenerate')}
                    </>
                  )}
                </Button>
              </>
            )}
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Departures Management Dialog */}
      <Dialog open={isDeparturesDialogOpen} onOpenChange={setIsDeparturesDialogOpen}>
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto ">
          <DialogHeader>
            <DialogTitle>{t('toursTab.departuresDialogTitle')}</DialogTitle>
            <DialogDescription>
              {selectedTourForDepartures?.title}
            </DialogDescription>
          </DialogHeader>
          {selectedTourForDepartures && (
            <DeparturesManagement 
              tourId={selectedTourForDepartures.id} 
              tourTitle={selectedTourForDepartures.title}
            />
          )}
        </DialogContent>
      </Dialog>

      {/* AI Departure Preview Dialog */}
      {selectedTourForAiPreview && (
        <DeparturePreview
          tourId={selectedTourForAiPreview.id}
          tourTitle={selectedTourForAiPreview.title}
          open={isAiDeparturePreviewOpen}
          onOpenChange={(open) => {
            setIsAiDeparturePreviewOpen(open);
            if (!open) setSelectedTourForAiPreview(null);
          }}
          onConfirmed={() => {
            utils.tours.list.invalidate();
          }}
        />
      )}

      {/* Preview Generated Tour Dialog - Enhanced */}
      <Dialog open={isPreviewDialogOpen} onOpenChange={setIsPreviewDialogOpen}>
        <DialogContent className="max-w-5xl max-h-[90vh] overflow-y-auto ">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-purple-600" />
              {t('toursTab.previewTitle')}
            </DialogTitle>
            <DialogDescription>
              {t('toursTab.previewDesc')}
            </DialogDescription>
          </DialogHeader>
          {generatedTourData && (
            <div className="grid gap-6 py-4">
              {/* Hero Image Preview */}
              {generatedTourData.heroImage && (
                <div className="relative rounded-lg overflow-hidden">
                  <img 
                    src={generatedTourData.heroImage} 
                    alt="Hero" 
                    className="w-full h-48 object-cover rounded-lg"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" />
                  <div className="absolute bottom-4 left-4 right-4 text-white">
                    <h3 className="text-xl font-bold">{generatedTourData.poeticTitle || generatedTourData.title}</h3>
                    <p className="text-sm opacity-90 mt-1">{generatedTourData.heroSubtitle || generatedTourData.promotionText}</p>
                  </div>
                </div>
              )}

              {/* Basic Info */}
              <div className="bg-purple-50 rounded-lg p-4">
                <h3 className="font-semibold text-purple-900 mb-3">{t('toursTab.previewBasicInfo')}</h3>
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <span className="text-gray-500">{t('toursTab.previewTitle')}</span>
                    <span className="ml-2 font-medium">{generatedTourData.title}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">{t('toursTab.previewCode')}</span>
                    <span className="ml-2">{generatedTourData.productCode || '-'}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">{t('toursTab.previewPromo')}</span>
                    <span className="ml-2 text-red-600">{generatedTourData.promotionText || '-'}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">{t('toursTab.previewDays')}</span>
                    <span className="ml-2">{t('toursTab.previewDaysNights').replace('{days}', String(generatedTourData.duration)).replace('{nights}', String(generatedTourData.nights || (generatedTourData.duration - 1)))}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">{t('toursTab.previewPrice')}</span>
                    <span className="ml-2 font-bold text-lg text-green-600">NT$ {generatedTourData.price?.toLocaleString()}</span>
                  </div>
                </div>
              </div>

              {/* Location Info */}
              <div className="bg-blue-50 rounded-lg p-4">
                <h3 className="font-semibold text-blue-900 mb-3">{t('toursTab.previewLocation')}</h3>
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <span className="text-gray-500">{t('toursTab.previewDepartureCity')}</span>
                    <span className="ml-2">{generatedTourData.departureCountry} / {generatedTourData.departureCity}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">{t('toursTab.previewDepartureAirport')}</span>
                    <span className="ml-2">{generatedTourData.departureAirportCode} {generatedTourData.departureAirportName}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">{t('toursTab.previewDestCity')}</span>
                    <span className="ml-2 font-medium">{generatedTourData.destinationCountry} / {generatedTourData.destinationCity}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">{t('toursTab.previewDestAirport')}</span>
                    <span className="ml-2">{generatedTourData.destinationAirportCode} {generatedTourData.destinationAirportName}</span>
                  </div>
                </div>
              </div>

              {/* Itinerary Preview */}
              {generatedTourData.itineraryDetailed && (
                <div className="bg-amber-50 rounded-lg p-4">
                  <h3 className="font-semibold text-amber-900 mb-3">{t('toursTab.previewItinerary')}</h3>
                  <div className="space-y-2 text-sm max-h-40 overflow-y-auto">
                    {(() => {
                      try {
                        const itinerary = JSON.parse(generatedTourData.itineraryDetailed);
                        return itinerary.slice(0, 3).map((day: any, index: number) => (
                          <div key={index} className="flex gap-2">
                            <span className="font-medium text-amber-700">Day {day.day || index + 1}:</span>
                            <span className="text-gray-700">{day.title || day.description?.substring(0, 50) || '-'}</span>
                          </div>
                        ));
                      } catch {
                        return <p className="text-gray-500">{t('toursTab.previewParseError')}</p>;
                      }
                    })()
                    }
                    {(() => {  try {
                        const itinerary = JSON.parse(generatedTourData.itineraryDetailed);
                        if (itinerary.length > 3) {
                          return <p className="text-amber-600 text-xs">{t('toursTab.previewMoreDays').replace('{count}', String(itinerary.length - 3))}</p>;
                        }
                      } catch {
                        return null;
                      }
                    })()}
                  </div>
                </div>
              )}

              {/* Cost Explanation Preview */}
              {generatedTourData.costExplanation && (
                <div className="bg-green-50 rounded-lg p-4">
                  <h3 className="font-semibold text-green-900 mb-3">{t('toursTab.previewCost')}</h3>
                  <div className="grid grid-cols-2 gap-4 text-sm">
                    {(() => {
                      try {
                        const cost = JSON.parse(generatedTourData.costExplanation);
                        return (
                          <>
                            <div>
                              <span className="text-gray-500">{t('toursTab.previewIncludes')}</span>
                              <span className="ml-2">{t('toursTab.previewIncludesCount').replace('{count}', String(cost.includes?.length || 0))}</span>
                            </div>
                            <div>
                              <span className="text-gray-500">{t('toursTab.previewExcludes')}</span>
                              <span className="ml-2">{t('toursTab.previewExcludesCount').replace('{count}', String(cost.excludes?.length || 0))}</span>
                            </div>
                          </>
                        );
                      } catch {
                        return <p className="text-gray-500">{t('toursTab.previewCostParseError')}</p>;
                      }
                    })()}
                  </div>
                </div>
              )}

              {/* Description */}
              <div className="bg-gray-50 rounded-lg p-4">
                <h3 className="font-semibold text-gray-900 mb-3">{t('toursTab.previewDescription')}</h3>
                <p className="text-sm text-gray-700 whitespace-pre-wrap line-clamp-4">{generatedTourData.description}</p>
              </div>

              {/* Source URL */}
              {isAdmin && generatedTourData.sourceUrl && (
                <div className="text-xs text-gray-400 flex items-center gap-2">
                  <ExternalLink className="h-3 w-3" />
                  {t('toursTab.sourceLabel')}
                  <a 
                    href={generatedTourData.sourceUrl} 
                    target="_blank" 
                    rel="noopener noreferrer" 
                    className="text-blue-500 hover:underline"
                  >
                    {generatedTourData.sourceUrl}
                  </a>
                </div>
              )}

              {/* Execution Report */}
              {generatedTourData.executionReport && (
                <details className="text-xs text-gray-400">
                  <summary className="cursor-pointer hover:text-gray-600">{t('toursTab.viewReport')}</summary>
                  <pre className="mt-2 p-2 bg-gray-100 rounded-lg overflow-x-auto whitespace-pre-wrap">
                    {generatedTourData.executionReport}
                  </pre>
                </details>
              )}
            </div>
          )}
          <DialogFooter className="flex gap-2">
            <Button
              variant="outline"
              onClick={() => {
                setIsPreviewDialogOpen(false);
                setGeneratedTourData(null);
                setAutoGenerateUrl("");
                setExtractionStep(0);
              }}
              className=""
            >
              {t('common.cancel')}
            </Button>
            <Button
              variant="outline"
              onClick={handleRegenerate}
              className="rounded-full border-purple-300 text-purple-700 hover:bg-purple-50"
            >
              <RefreshCw className="h-4 w-4 mr-2" />
              {t('toursTab.regenerate')}
            </Button>
            <Button
              variant="outline"
              onClick={() => {
                setIsPreviewDialogOpen(false);
                setIsEditDialogOpen2(true);
              }}
              className="rounded-full border-purple-300 text-purple-700 hover:bg-purple-50"
            >
              <Edit className="h-4 w-4 mr-2" />
              {t('common.edit')}
            </Button>
            <Button
              onClick={handleConfirmGeneratedTour}
              disabled={saveFromPreviewMutation.isPending}
              className="bg-purple-600 text-white hover:bg-purple-700 rounded-full"
            >
              {saveFromPreviewMutation.isPending ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  {t('toursTab.saving')}
                </>
              ) : (
                t('toursTab.saveDirectly')
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Edit Generated Tour Dialog */}
      <TourEditDialog
        open={isEditDialogOpen2}
        onOpenChange={setIsEditDialogOpen2}
        tourData={generatedTourData}
        onSave={(editedData) => {
          console.log("[EditDialog] Saving edited tour data:", editedData);
          saveFromPreviewMutation.mutate({ tourData: editedData });
          setIsEditDialogOpen2(false);
        }}
        isSaving={saveFromPreviewMutation.isPending}
      />

      {/* Full Edit Dialog for Existing Tours */}
      <TourEditDialog
        open={isFullEditDialogOpen}
        onOpenChange={setIsFullEditDialogOpen}
        tourData={selectedTourForEdit}
        onSave={(editedData) => {
          console.log("[FullEditDialog] Saving edited tour data:", editedData);
          if (selectedTourId) {
            updateTourMutation.mutate({
              id: selectedTourId,
              ...editedData,
            });
            // Dialog closes in onSuccess callback
          }
        }}
        isSaving={updateTourMutation.isPending}
      />
    </div>
  );
}

// Tour Form Component
function TourForm({
  formData,
  setFormData,
}: {
  formData: TourFormData;
  setFormData: React.Dispatch<React.SetStateAction<TourFormData>>;
}) {
  const { t } = useLocale();
  return (
    <div className="grid gap-6 py-4">
      {/* 基本資訊區塊 */}
      <div className="space-y-4">
        <div className="flex items-center gap-2 pb-2 border-b border-gray-200">
          <div className="h-1.5 w-1.5 rounded-full bg-black"></div>
          <h3 className="text-sm font-semibold text-gray-900">{t('toursTab.formBasicInfo')}</h3>
        </div>
        
        <div className="grid gap-4">
          <div className="grid gap-2">
            <Label htmlFor="title" className="text-sm font-medium text-gray-700">
              {t('toursTab.formTourTitle')} <span className="text-red-500">*</span>
            </Label>
            <Input
              id="title"
              value={formData.title}
              onChange={(e) =>
                setFormData({ ...formData, title: e.target.value })
              }
              placeholder={t('toursTab.formTourTitlePlaceholder')}
              className=""
            />
          </div>
          
          <div className="grid grid-cols-2 gap-4">
            <div className="grid gap-2">
              <Label htmlFor="destinationCountry" className="text-sm font-medium text-gray-700">
                {t('toursTab.formDestCountry')} <span className="text-red-500">*</span>
              </Label>
              <Input
                id="destinationCountry"
                value={formData.destinationCountry}
                onChange={(e) =>
                  setFormData({ ...formData, destinationCountry: e.target.value })
                }
                placeholder={t('toursTab.formDestCountryPlaceholder')}
                className=""
              />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="destinationCity" className="text-sm font-medium text-gray-700">
              {t('toursTab.formDestCity')}
            </Label>
              <Input
                id="destinationCity"
                value={formData.destinationCity}
                onChange={(e) =>
                  setFormData({ ...formData, destinationCity: e.target.value })
                }
                placeholder={t('toursTab.formDestCityPlaceholder')}
                className=""
              />
            </div>
          </div>

          <div className="grid gap-2">
            <Label htmlFor="destination" className="text-sm font-medium text-gray-700">
              {t('toursTab.formDestDisplay')} <span className="text-red-500">*</span>
            </Label>
            <Input
              id="destination"
              value={formData.destination}
              onChange={(e) =>
                setFormData({ ...formData, destination: e.target.value })
              }
                placeholder={t('toursTab.formDestDisplayPlaceholder')}
              className=""
            />
          </div>
        </div>
      </div>

      {/* 行程詳情區塊 */}
      <div className="space-y-4">
        <div className="flex items-center gap-2 pb-2 border-b border-gray-200">
          <div className="h-1.5 w-1.5 rounded-full bg-black"></div>
          <h3 className="text-sm font-semibold text-gray-900">{t('toursTab.formTourDetails')}</h3>
        </div>
        
        <div className="grid gap-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="grid gap-2">
              <Label htmlFor="duration" className="text-sm font-medium text-gray-700">
                {t('toursTab.formDays')}
              </Label>
              <Input
                id="duration"
                type="number"
                min={1}
                value={formData.duration}
                onChange={(e) =>
                  setFormData({ ...formData, duration: parseInt(e.target.value) || 1 })
                }
                className=""
              />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="price" className="text-sm font-medium text-gray-700">
                {t('toursTab.formPrice')}
              </Label>
              <Input
                id="price"
                type="number"
                min={0}
                value={formData.price}
                onChange={(e) =>
                  setFormData({ ...formData, price: parseInt(e.target.value) || 0 })
                }
                className=""
              />
            </div>
          </div>

          <div className="grid gap-2">
            <Label htmlFor="description" className="text-sm font-medium text-gray-700">
              {t('toursTab.formDescription')}
            </Label>
            <Textarea
              id="description"
              value={formData.description}
              onChange={(e) =>
                setFormData({ ...formData, description: e.target.value })
              }
              placeholder={t('toursTab.formDescriptionPlaceholder')}
              rows={3}
              className="rounded-lg"
            />
          </div>

          <div className="grid gap-2">
            <Label htmlFor="imageUrl" className="text-sm font-medium text-gray-700">
              {t('toursTab.formImageUrl')}
            </Label>
            <Input
              id="imageUrl"
              value={formData.imageUrl}
              onChange={(e) =>
                setFormData({ ...formData, imageUrl: e.target.value })
              }
              placeholder="https://..."
              className=""
            />
          </div>
        </div>
      </div>

      {/* 分類與狀態區塊 */}
      <div className="space-y-4">
        <div className="flex items-center gap-2 pb-2 border-b border-gray-200">
          <div className="h-1.5 w-1.5 rounded-full bg-black"></div>
          <h3 className="text-sm font-semibold text-gray-900">{t('toursTab.formCategoryStatus')}</h3>
        </div>
        
        <div className="grid grid-cols-2 gap-4">
          <div className="grid gap-2">
            <Label htmlFor="category" className="text-sm font-medium text-gray-700">
              {t('toursTab.formCategory')}
            </Label>
            <Select
              value={formData.category}
              onValueChange={(v: any) => setFormData({ ...formData, category: v })}
            >
              <SelectTrigger className="">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="group">{t('toursTab.categoryGroup')}</SelectItem>
                <SelectItem value="custom">{t('toursTab.categoryCustom')}</SelectItem>
                <SelectItem value="package">{t('toursTab.categoryPackage')}</SelectItem>
                <SelectItem value="cruise">{t('toursTab.categoryCruise')}</SelectItem>
                <SelectItem value="theme">{t('toursTab.categoryTheme')}</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="grid gap-2">
            <Label htmlFor="status" className="text-sm font-medium text-gray-700">
              {t('toursTab.formStatus')}
            </Label>
            <Select
              value={formData.status}
              onValueChange={(v: any) => setFormData({ ...formData, status: v })}
            >
              <SelectTrigger className="">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="active">{t('toursTab.statusActive')}</SelectItem>
                <SelectItem value="inactive">{t('toursTab.statusInactive')}</SelectItem>
                <SelectItem value="soldout">{t('toursTab.statusSoldOut')}</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
      </div>
    </div>
  );
}
